package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import webgpu.WebgpuLibrary.WGPUCompositeAlphaMode;
import webgpu.WebgpuLibrary.WGPUDevice;
import webgpu.WebgpuLibrary.WGPUPresentMode;
import webgpu.WebgpuLibrary.WGPUTextureFormat;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSurfaceConfiguration extends StructObject {
	public WGPUSurfaceConfiguration() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUSurfaceConfiguration nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUDevice
	@Field(1) 
	public WGPUDevice device() {
		return this.io.getTypedPointerField(this, 1);
	}
	/// C type : WGPUDevice
	@Field(1) 
	public WGPUSurfaceConfiguration device(WGPUDevice device) {
		this.io.setPointerField(this, 1, device);
		return this;
	}
	/// C type : WGPUTextureFormat
	@Field(2) 
	public IntValuedEnum<WGPUTextureFormat > format() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : WGPUTextureFormat
	@Field(2) 
	public WGPUSurfaceConfiguration format(IntValuedEnum<WGPUTextureFormat > format) {
		this.io.setEnumField(this, 2, format);
		return this;
	}
	/// C type : WGPUTextureUsage
	@Field(3) 
	public long usage() {
		return this.io.getLongField(this, 3);
	}
	/// C type : WGPUTextureUsage
	@Field(3) 
	public WGPUSurfaceConfiguration usage(long usage) {
		this.io.setLongField(this, 3, usage);
		return this;
	}
	@Ptr 
	@Field(4) 
	public long viewFormatCount() {
		return this.io.getSizeTField(this, 4);
	}
	@Ptr 
	@Field(4) 
	public WGPUSurfaceConfiguration viewFormatCount(long viewFormatCount) {
		this.io.setSizeTField(this, 4, viewFormatCount);
		return this;
	}
	/// C type : const WGPUTextureFormat*
	@Field(5) 
	public Pointer<IntValuedEnum<WGPUTextureFormat > > viewFormats() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : const WGPUTextureFormat*
	@Field(5) 
	public WGPUSurfaceConfiguration viewFormats(Pointer<IntValuedEnum<WGPUTextureFormat > > viewFormats) {
		this.io.setPointerField(this, 5, viewFormats);
		return this;
	}
	/// C type : WGPUCompositeAlphaMode
	@Field(6) 
	public IntValuedEnum<WGPUCompositeAlphaMode > alphaMode() {
		return this.io.getEnumField(this, 6);
	}
	/// C type : WGPUCompositeAlphaMode
	@Field(6) 
	public WGPUSurfaceConfiguration alphaMode(IntValuedEnum<WGPUCompositeAlphaMode > alphaMode) {
		this.io.setEnumField(this, 6, alphaMode);
		return this;
	}
	@Field(7) 
	public int width() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public WGPUSurfaceConfiguration width(int width) {
		this.io.setIntField(this, 7, width);
		return this;
	}
	@Field(8) 
	public int height() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public WGPUSurfaceConfiguration height(int height) {
		this.io.setIntField(this, 8, height);
		return this;
	}
	/// C type : WGPUPresentMode
	@Field(9) 
	public IntValuedEnum<WGPUPresentMode > presentMode() {
		return this.io.getEnumField(this, 9);
	}
	/// C type : WGPUPresentMode
	@Field(9) 
	public WGPUSurfaceConfiguration presentMode(IntValuedEnum<WGPUPresentMode > presentMode) {
		this.io.setEnumField(this, 9, presentMode);
		return this;
	}
	public WGPUSurfaceConfiguration(Pointer pointer) {
		super(pointer);
	}
}
