package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSharedFenceMTLSharedEventExportInfo extends StructObject {
	public WGPUSharedFenceMTLSharedEventExportInfo() {
		super();
	}
	/// C type : WGPUChainedStructOut
	@Field(0) 
	public WGPUChainedStructOut chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStructOut
	@Field(0) 
	public WGPUSharedFenceMTLSharedEventExportInfo chain(WGPUChainedStructOut chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : void*
	@Field(1) 
	public Pointer<? > sharedEvent() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : void*
	@Field(1) 
	public WGPUSharedFenceMTLSharedEventExportInfo sharedEvent(Pointer<? > sharedEvent) {
		this.io.setPointerField(this, 1, sharedEvent);
		return this;
	}
	public WGPUSharedFenceMTLSharedEventExportInfo(Pointer pointer) {
		super(pointer);
	}
}
