package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUExtent2D extends StructObject {
	public WGPUExtent2D() {
		super();
	}
	@Field(0) 
	public int width() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public WGPUExtent2D width(int width) {
		this.io.setIntField(this, 0, width);
		return this;
	}
	@Field(1) 
	public int height() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUExtent2D height(int height) {
		this.io.setIntField(this, 1, height);
		return this;
	}
	public WGPUExtent2D(Pointer pointer) {
		super(pointer);
	}
}
