package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import webgpu.WebgpuLibrary.WGPUVertexStepMode;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUVertexBufferLayout extends StructObject {
	public WGPUVertexBufferLayout() {
		super();
	}
	@Field(0) 
	public long arrayStride() {
		return this.io.getLongField(this, 0);
	}
	@Field(0) 
	public WGPUVertexBufferLayout arrayStride(long arrayStride) {
		this.io.setLongField(this, 0, arrayStride);
		return this;
	}
	/// C type : WGPUVertexStepMode
	@Field(1) 
	public IntValuedEnum<WGPUVertexStepMode > stepMode() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : WGPUVertexStepMode
	@Field(1) 
	public WGPUVertexBufferLayout stepMode(IntValuedEnum<WGPUVertexStepMode > stepMode) {
		this.io.setEnumField(this, 1, stepMode);
		return this;
	}
	@Ptr 
	@Field(2) 
	public long attributeCount() {
		return this.io.getSizeTField(this, 2);
	}
	@Ptr 
	@Field(2) 
	public WGPUVertexBufferLayout attributeCount(long attributeCount) {
		this.io.setSizeTField(this, 2, attributeCount);
		return this;
	}
	/// C type : const WGPUVertexAttribute*
	@Field(3) 
	public Pointer<WGPUVertexAttribute > attributes() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : const WGPUVertexAttribute*
	@Field(3) 
	public WGPUVertexBufferLayout attributes(Pointer<WGPUVertexAttribute > attributes) {
		this.io.setPointerField(this, 3, attributes);
		return this;
	}
	public WGPUVertexBufferLayout(Pointer pointer) {
		super(pointer);
	}
}
