package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUFutureWaitInfo extends StructObject {
	public WGPUFutureWaitInfo() {
		super();
	}
	/// C type : WGPUFuture
	@Field(0) 
	public WGPUFuture future() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUFuture
	@Field(0) 
	public WGPUFutureWaitInfo future(WGPUFuture future) {
		this.io.setNativeObjectField(this, 0, future);
		return this;
	}
	/// C type : WGPUBool
	@Field(1) 
	public int completed() {
		return this.io.getIntField(this, 1);
	}
	/// C type : WGPUBool
	@Field(1) 
	public WGPUFutureWaitInfo completed(int completed) {
		this.io.setIntField(this, 1, completed);
		return this;
	}
	public WGPUFutureWaitInfo(Pointer pointer) {
		super(pointer);
	}
}
