package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUOrigin2D extends StructObject {
	public WGPUOrigin2D() {
		super();
	}
	@Field(0) 
	public int x() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public WGPUOrigin2D x(int x) {
		this.io.setIntField(this, 0, x);
		return this;
	}
	@Field(1) 
	public int y() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUOrigin2D y(int y) {
		this.io.setIntField(this, 1, y);
		return this;
	}
	public WGPUOrigin2D(Pointer pointer) {
		super(pointer);
	}
}
