package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUAdapterType;
import webgpu.WebgpuLibrary.WGPUBackendType;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUAdapterInfo extends StructObject {
	public WGPUAdapterInfo() {
		super();
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public Pointer<WGPUChainedStructOut > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public WGPUAdapterInfo nextInChain(Pointer<WGPUChainedStructOut > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > vendor() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPUAdapterInfo vendor(Pointer<Byte > vendor) {
		this.io.setPointerField(this, 1, vendor);
		return this;
	}
	/// C type : const char*
	@Field(2) 
	public Pointer<Byte > architecture() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : const char*
	@Field(2) 
	public WGPUAdapterInfo architecture(Pointer<Byte > architecture) {
		this.io.setPointerField(this, 2, architecture);
		return this;
	}
	/// C type : const char*
	@Field(3) 
	public Pointer<Byte > device() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : const char*
	@Field(3) 
	public WGPUAdapterInfo device(Pointer<Byte > device) {
		this.io.setPointerField(this, 3, device);
		return this;
	}
	/// C type : const char*
	@Field(4) 
	public Pointer<Byte > description() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : const char*
	@Field(4) 
	public WGPUAdapterInfo description(Pointer<Byte > description) {
		this.io.setPointerField(this, 4, description);
		return this;
	}
	/// C type : WGPUBackendType
	@Field(5) 
	public IntValuedEnum<WGPUBackendType > backendType() {
		return this.io.getEnumField(this, 5);
	}
	/// C type : WGPUBackendType
	@Field(5) 
	public WGPUAdapterInfo backendType(IntValuedEnum<WGPUBackendType > backendType) {
		this.io.setEnumField(this, 5, backendType);
		return this;
	}
	/// C type : WGPUAdapterType
	@Field(6) 
	public IntValuedEnum<WGPUAdapterType > adapterType() {
		return this.io.getEnumField(this, 6);
	}
	/// C type : WGPUAdapterType
	@Field(6) 
	public WGPUAdapterInfo adapterType(IntValuedEnum<WGPUAdapterType > adapterType) {
		this.io.setEnumField(this, 6, adapterType);
		return this;
	}
	@Field(7) 
	public int vendorID() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public WGPUAdapterInfo vendorID(int vendorID) {
		this.io.setIntField(this, 7, vendorID);
		return this;
	}
	@Field(8) 
	public int deviceID() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public WGPUAdapterInfo deviceID(int deviceID) {
		this.io.setIntField(this, 8, deviceID);
		return this;
	}
	/// C type : WGPUBool
	@Field(9) 
	public int compatibilityMode() {
		return this.io.getIntField(this, 9);
	}
	/// C type : WGPUBool
	@Field(9) 
	public WGPUAdapterInfo compatibilityMode(int compatibilityMode) {
		this.io.setIntField(this, 9, compatibilityMode);
		return this;
	}
	public WGPUAdapterInfo(Pointer pointer) {
		super(pointer);
	}
}
