package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUExternalTextureRotation;
import webgpu.WebgpuLibrary.WGPUTextureView;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUExternalTextureDescriptor extends StructObject {
	public WGPUExternalTextureDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUExternalTextureDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > label() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPUExternalTextureDescriptor label(Pointer<Byte > label) {
		this.io.setPointerField(this, 1, label);
		return this;
	}
	/// C type : WGPUTextureView
	@Field(2) 
	public WGPUTextureView plane0() {
		return this.io.getTypedPointerField(this, 2);
	}
	/// C type : WGPUTextureView
	@Field(2) 
	public WGPUExternalTextureDescriptor plane0(WGPUTextureView plane0) {
		this.io.setPointerField(this, 2, plane0);
		return this;
	}
	/// C type : WGPUTextureView
	@Field(3) 
	public WGPUTextureView plane1() {
		return this.io.getTypedPointerField(this, 3);
	}
	/// C type : WGPUTextureView
	@Field(3) 
	public WGPUExternalTextureDescriptor plane1(WGPUTextureView plane1) {
		this.io.setPointerField(this, 3, plane1);
		return this;
	}
	/// C type : WGPUOrigin2D
	@Field(4) 
	public WGPUOrigin2D visibleOrigin() {
		return this.io.getNativeObjectField(this, 4);
	}
	/// C type : WGPUOrigin2D
	@Field(4) 
	public WGPUExternalTextureDescriptor visibleOrigin(WGPUOrigin2D visibleOrigin) {
		this.io.setNativeObjectField(this, 4, visibleOrigin);
		return this;
	}
	/// C type : WGPUExtent2D
	@Field(5) 
	public WGPUExtent2D visibleSize() {
		return this.io.getNativeObjectField(this, 5);
	}
	/// C type : WGPUExtent2D
	@Field(5) 
	public WGPUExternalTextureDescriptor visibleSize(WGPUExtent2D visibleSize) {
		this.io.setNativeObjectField(this, 5, visibleSize);
		return this;
	}
	/// C type : WGPUBool
	@Field(6) 
	public int doYuvToRgbConversionOnly() {
		return this.io.getIntField(this, 6);
	}
	/// C type : WGPUBool
	@Field(6) 
	public WGPUExternalTextureDescriptor doYuvToRgbConversionOnly(int doYuvToRgbConversionOnly) {
		this.io.setIntField(this, 6, doYuvToRgbConversionOnly);
		return this;
	}
	/// C type : const float*
	@Field(7) 
	public Pointer<Float > yuvToRgbConversionMatrix() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : const float*
	@Field(7) 
	public WGPUExternalTextureDescriptor yuvToRgbConversionMatrix(Pointer<Float > yuvToRgbConversionMatrix) {
		this.io.setPointerField(this, 7, yuvToRgbConversionMatrix);
		return this;
	}
	/// C type : const float*
	@Field(8) 
	public Pointer<Float > srcTransferFunctionParameters() {
		return this.io.getPointerField(this, 8);
	}
	/// C type : const float*
	@Field(8) 
	public WGPUExternalTextureDescriptor srcTransferFunctionParameters(Pointer<Float > srcTransferFunctionParameters) {
		this.io.setPointerField(this, 8, srcTransferFunctionParameters);
		return this;
	}
	/// C type : const float*
	@Field(9) 
	public Pointer<Float > dstTransferFunctionParameters() {
		return this.io.getPointerField(this, 9);
	}
	/// C type : const float*
	@Field(9) 
	public WGPUExternalTextureDescriptor dstTransferFunctionParameters(Pointer<Float > dstTransferFunctionParameters) {
		this.io.setPointerField(this, 9, dstTransferFunctionParameters);
		return this;
	}
	/// C type : const float*
	@Field(10) 
	public Pointer<Float > gamutConversionMatrix() {
		return this.io.getPointerField(this, 10);
	}
	/// C type : const float*
	@Field(10) 
	public WGPUExternalTextureDescriptor gamutConversionMatrix(Pointer<Float > gamutConversionMatrix) {
		this.io.setPointerField(this, 10, gamutConversionMatrix);
		return this;
	}
	/// C type : WGPUBool
	@Field(11) 
	public int mirrored() {
		return this.io.getIntField(this, 11);
	}
	/// C type : WGPUBool
	@Field(11) 
	public WGPUExternalTextureDescriptor mirrored(int mirrored) {
		this.io.setIntField(this, 11, mirrored);
		return this;
	}
	/// C type : WGPUExternalTextureRotation
	@Field(12) 
	public IntValuedEnum<WGPUExternalTextureRotation > rotation() {
		return this.io.getEnumField(this, 12);
	}
	/// C type : WGPUExternalTextureRotation
	@Field(12) 
	public WGPUExternalTextureDescriptor rotation(IntValuedEnum<WGPUExternalTextureRotation > rotation) {
		this.io.setEnumField(this, 12, rotation);
		return this;
	}
	public WGPUExternalTextureDescriptor(Pointer pointer) {
		super(pointer);
	}
}
