package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUColor extends StructObject {
	public WGPUColor() {
		super();
	}
	@Field(0) 
	public double r() {
		return this.io.getDoubleField(this, 0);
	}
	@Field(0) 
	public WGPUColor r(double r) {
		this.io.setDoubleField(this, 0, r);
		return this;
	}
	@Field(1) 
	public double g() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public WGPUColor g(double g) {
		this.io.setDoubleField(this, 1, g);
		return this;
	}
	@Field(2) 
	public double b() {
		return this.io.getDoubleField(this, 2);
	}
	@Field(2) 
	public WGPUColor b(double b) {
		this.io.setDoubleField(this, 2, b);
		return this;
	}
	@Field(3) 
	public double a() {
		return this.io.getDoubleField(this, 3);
	}
	@Field(3) 
	public WGPUColor a(double a) {
		this.io.setDoubleField(this, 3, a);
		return this;
	}
	public WGPUColor(Pointer pointer) {
		super(pointer);
	}
}
