package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUPowerPreference;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUDawnAdapterPropertiesPowerPreference extends StructObject {
	public WGPUDawnAdapterPropertiesPowerPreference() {
		super();
	}
	/// C type : WGPUChainedStructOut
	@Field(0) 
	public WGPUChainedStructOut chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStructOut
	@Field(0) 
	public WGPUDawnAdapterPropertiesPowerPreference chain(WGPUChainedStructOut chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : WGPUPowerPreference
	@Field(1) 
	public IntValuedEnum<WGPUPowerPreference > powerPreference() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : WGPUPowerPreference
	@Field(1) 
	public WGPUDawnAdapterPropertiesPowerPreference powerPreference(IntValuedEnum<WGPUPowerPreference > powerPreference) {
		this.io.setEnumField(this, 1, powerPreference);
		return this;
	}
	public WGPUDawnAdapterPropertiesPowerPreference(Pointer pointer) {
		super(pointer);
	}
}
