package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUExternalTexture;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUImageCopyExternalTexture extends StructObject {
	public WGPUImageCopyExternalTexture() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUImageCopyExternalTexture nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUExternalTexture
	@Field(1) 
	public WGPUExternalTexture externalTexture() {
		return this.io.getTypedPointerField(this, 1);
	}
	/// C type : WGPUExternalTexture
	@Field(1) 
	public WGPUImageCopyExternalTexture externalTexture(WGPUExternalTexture externalTexture) {
		this.io.setPointerField(this, 1, externalTexture);
		return this;
	}
	/// C type : WGPUOrigin3D
	@Field(2) 
	public WGPUOrigin3D origin() {
		return this.io.getNativeObjectField(this, 2);
	}
	/// C type : WGPUOrigin3D
	@Field(2) 
	public WGPUImageCopyExternalTexture origin(WGPUOrigin3D origin) {
		this.io.setNativeObjectField(this, 2, origin);
		return this;
	}
	/// C type : WGPUExtent2D
	@Field(3) 
	public WGPUExtent2D naturalSize() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : WGPUExtent2D
	@Field(3) 
	public WGPUImageCopyExternalTexture naturalSize(WGPUExtent2D naturalSize) {
		this.io.setNativeObjectField(this, 3, naturalSize);
		return this;
	}
	public WGPUImageCopyExternalTexture(Pointer pointer) {
		super(pointer);
	}
}
