package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUAHardwareBufferProperties extends StructObject {
	public WGPUAHardwareBufferProperties() {
		super();
	}
	/// C type : WGPUYCbCrVkDescriptor
	@Field(0) 
	public WGPUYCbCrVkDescriptor yCbCrInfo() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUYCbCrVkDescriptor
	@Field(0) 
	public WGPUAHardwareBufferProperties yCbCrInfo(WGPUYCbCrVkDescriptor yCbCrInfo) {
		this.io.setNativeObjectField(this, 0, yCbCrInfo);
		return this;
	}
	public WGPUAHardwareBufferProperties(Pointer pointer) {
		super(pointer);
	}
}
