package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUDawnWGSLBlocklist extends StructObject {
	public WGPUDawnWGSLBlocklist() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUDawnWGSLBlocklist chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Ptr 
	@Field(1) 
	public long blocklistedFeatureCount() {
		return this.io.getSizeTField(this, 1);
	}
	@Ptr 
	@Field(1) 
	public WGPUDawnWGSLBlocklist blocklistedFeatureCount(long blocklistedFeatureCount) {
		this.io.setSizeTField(this, 1, blocklistedFeatureCount);
		return this;
	}
	/// C type : const char**
	@Field(2) 
	public Pointer<Pointer<Byte > > blocklistedFeatures() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : const char**
	@Field(2) 
	public WGPUDawnWGSLBlocklist blocklistedFeatures(Pointer<Pointer<Byte > > blocklistedFeatures) {
		this.io.setPointerField(this, 2, blocklistedFeatures);
		return this;
	}
	public WGPUDawnWGSLBlocklist(Pointer pointer) {
		super(pointer);
	}
}
