package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUShaderModuleSPIRVDescriptor extends StructObject {
	public WGPUShaderModuleSPIRVDescriptor() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUShaderModuleSPIRVDescriptor chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Field(1) 
	public int codeSize() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUShaderModuleSPIRVDescriptor codeSize(int codeSize) {
		this.io.setIntField(this, 1, codeSize);
		return this;
	}
	/// C type : const uint32_t*
	@Field(2) 
	public Pointer<Integer > code() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : const uint32_t*
	@Field(2) 
	public WGPUShaderModuleSPIRVDescriptor code(Pointer<Integer > code) {
		this.io.setPointerField(this, 2, code);
		return this;
	}
	public WGPUShaderModuleSPIRVDescriptor(Pointer pointer) {
		super(pointer);
	}
}
