package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUUncapturedErrorCallback;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUUncapturedErrorCallbackInfo2 extends StructObject {
	public WGPUUncapturedErrorCallbackInfo2() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUUncapturedErrorCallbackInfo2 nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUUncapturedErrorCallback
	@Field(1) 
	public Pointer<WGPUUncapturedErrorCallback > callback() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : WGPUUncapturedErrorCallback
	@Field(1) 
	public WGPUUncapturedErrorCallbackInfo2 callback(Pointer<WGPUUncapturedErrorCallback > callback) {
		this.io.setPointerField(this, 1, callback);
		return this;
	}
	/// C type : void*
	@Field(2) 
	public Pointer<? > userdata1() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : void*
	@Field(2) 
	public WGPUUncapturedErrorCallbackInfo2 userdata1(Pointer<? > userdata1) {
		this.io.setPointerField(this, 2, userdata1);
		return this;
	}
	/// C type : void*
	@Field(3) 
	public Pointer<? > userdata2() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : void*
	@Field(3) 
	public WGPUUncapturedErrorCallbackInfo2 userdata2(Pointer<? > userdata2) {
		this.io.setPointerField(this, 3, userdata2);
		return this;
	}
	public WGPUUncapturedErrorCallbackInfo2(Pointer pointer) {
		super(pointer);
	}
}
