package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPURenderPassPixelLocalStorage extends StructObject {
	public WGPURenderPassPixelLocalStorage() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPURenderPassPixelLocalStorage chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Field(1) 
	public long totalPixelLocalStorageSize() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public WGPURenderPassPixelLocalStorage totalPixelLocalStorageSize(long totalPixelLocalStorageSize) {
		this.io.setLongField(this, 1, totalPixelLocalStorageSize);
		return this;
	}
	@Ptr 
	@Field(2) 
	public long storageAttachmentCount() {
		return this.io.getSizeTField(this, 2);
	}
	@Ptr 
	@Field(2) 
	public WGPURenderPassPixelLocalStorage storageAttachmentCount(long storageAttachmentCount) {
		this.io.setSizeTField(this, 2, storageAttachmentCount);
		return this;
	}
	/// C type : const WGPURenderPassStorageAttachment*
	@Field(3) 
	public Pointer<WGPURenderPassStorageAttachment > storageAttachments() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : const WGPURenderPassStorageAttachment*
	@Field(3) 
	public WGPURenderPassPixelLocalStorage storageAttachments(Pointer<WGPURenderPassStorageAttachment > storageAttachments) {
		this.io.setPointerField(this, 3, storageAttachments);
		return this;
	}
	public WGPURenderPassPixelLocalStorage(Pointer pointer) {
		super(pointer);
	}
}
