package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSharedTextureMemoryDmaBufDescriptor extends StructObject {
	public WGPUSharedTextureMemoryDmaBufDescriptor() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUSharedTextureMemoryDmaBufDescriptor chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : WGPUExtent3D
	@Field(1) 
	public WGPUExtent3D size() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : WGPUExtent3D
	@Field(1) 
	public WGPUSharedTextureMemoryDmaBufDescriptor size(WGPUExtent3D size) {
		this.io.setNativeObjectField(this, 1, size);
		return this;
	}
	@Field(2) 
	public int drmFormat() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public WGPUSharedTextureMemoryDmaBufDescriptor drmFormat(int drmFormat) {
		this.io.setIntField(this, 2, drmFormat);
		return this;
	}
	@Field(3) 
	public long drmModifier() {
		return this.io.getLongField(this, 3);
	}
	@Field(3) 
	public WGPUSharedTextureMemoryDmaBufDescriptor drmModifier(long drmModifier) {
		this.io.setLongField(this, 3, drmModifier);
		return this;
	}
	@Ptr 
	@Field(4) 
	public long planeCount() {
		return this.io.getSizeTField(this, 4);
	}
	@Ptr 
	@Field(4) 
	public WGPUSharedTextureMemoryDmaBufDescriptor planeCount(long planeCount) {
		this.io.setSizeTField(this, 4, planeCount);
		return this;
	}
	/// C type : const WGPUSharedTextureMemoryDmaBufPlane*
	@Field(5) 
	public Pointer<WGPUSharedTextureMemoryDmaBufPlane > planes() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : const WGPUSharedTextureMemoryDmaBufPlane*
	@Field(5) 
	public WGPUSharedTextureMemoryDmaBufDescriptor planes(Pointer<WGPUSharedTextureMemoryDmaBufPlane > planes) {
		this.io.setPointerField(this, 5, planes);
		return this;
	}
	public WGPUSharedTextureMemoryDmaBufDescriptor(Pointer pointer) {
		super(pointer);
	}
}
