package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSharedBufferMemoryProperties extends StructObject {
	public WGPUSharedBufferMemoryProperties() {
		super();
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public Pointer<WGPUChainedStructOut > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public WGPUSharedBufferMemoryProperties nextInChain(Pointer<WGPUChainedStructOut > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUBufferUsage
	@Field(1) 
	public long usage() {
		return this.io.getLongField(this, 1);
	}
	/// C type : WGPUBufferUsage
	@Field(1) 
	public WGPUSharedBufferMemoryProperties usage(long usage) {
		this.io.setLongField(this, 1, usage);
		return this;
	}
	@Field(2) 
	public long size() {
		return this.io.getLongField(this, 2);
	}
	@Field(2) 
	public WGPUSharedBufferMemoryProperties size(long size) {
		this.io.setLongField(this, 2, size);
		return this;
	}
	public WGPUSharedBufferMemoryProperties(Pointer pointer) {
		super(pointer);
	}
}
