package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUBackendType;
import webgpu.WebgpuLibrary.WGPUPowerPreference;
import webgpu.WebgpuLibrary.WGPUSurface;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPURequestAdapterOptions extends StructObject {
	public WGPURequestAdapterOptions() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPURequestAdapterOptions nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUSurface
	@Field(1) 
	public WGPUSurface compatibleSurface() {
		return this.io.getTypedPointerField(this, 1);
	}
	/// C type : WGPUSurface
	@Field(1) 
	public WGPURequestAdapterOptions compatibleSurface(WGPUSurface compatibleSurface) {
		this.io.setPointerField(this, 1, compatibleSurface);
		return this;
	}
	/// C type : WGPUPowerPreference
	@Field(2) 
	public IntValuedEnum<WGPUPowerPreference > powerPreference() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : WGPUPowerPreference
	@Field(2) 
	public WGPURequestAdapterOptions powerPreference(IntValuedEnum<WGPUPowerPreference > powerPreference) {
		this.io.setEnumField(this, 2, powerPreference);
		return this;
	}
	/// C type : WGPUBackendType
	@Field(3) 
	public IntValuedEnum<WGPUBackendType > backendType() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : WGPUBackendType
	@Field(3) 
	public WGPURequestAdapterOptions backendType(IntValuedEnum<WGPUBackendType > backendType) {
		this.io.setEnumField(this, 3, backendType);
		return this;
	}
	/// C type : WGPUBool
	@Field(4) 
	public int forceFallbackAdapter() {
		return this.io.getIntField(this, 4);
	}
	/// C type : WGPUBool
	@Field(4) 
	public WGPURequestAdapterOptions forceFallbackAdapter(int forceFallbackAdapter) {
		this.io.setIntField(this, 4, forceFallbackAdapter);
		return this;
	}
	/// C type : WGPUBool
	@Field(5) 
	public int compatibilityMode() {
		return this.io.getIntField(this, 5);
	}
	/// C type : WGPUBool
	@Field(5) 
	public WGPURequestAdapterOptions compatibilityMode(int compatibilityMode) {
		this.io.setIntField(this, 5, compatibilityMode);
		return this;
	}
	public WGPURequestAdapterOptions(Pointer pointer) {
		super(pointer);
	}
}
