package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSharedTextureMemoryAHardwareBufferDescriptor extends StructObject {
	public WGPUSharedTextureMemoryAHardwareBufferDescriptor() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUSharedTextureMemoryAHardwareBufferDescriptor chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : void*
	@Field(1) 
	public Pointer<? > handle() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : void*
	@Field(1) 
	public WGPUSharedTextureMemoryAHardwareBufferDescriptor handle(Pointer<? > handle) {
		this.io.setPointerField(this, 1, handle);
		return this;
	}
	/// C type : WGPUBool
	@Field(2) 
	public int useExternalFormat() {
		return this.io.getIntField(this, 2);
	}
	/// C type : WGPUBool
	@Field(2) 
	public WGPUSharedTextureMemoryAHardwareBufferDescriptor useExternalFormat(int useExternalFormat) {
		this.io.setIntField(this, 2, useExternalFormat);
		return this;
	}
	public WGPUSharedTextureMemoryAHardwareBufferDescriptor(Pointer pointer) {
		super(pointer);
	}
}
