package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUFilterMode;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUYCbCrVkDescriptor extends StructObject {
	public WGPUYCbCrVkDescriptor() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUYCbCrVkDescriptor chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Field(1) 
	public int vkFormat() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUYCbCrVkDescriptor vkFormat(int vkFormat) {
		this.io.setIntField(this, 1, vkFormat);
		return this;
	}
	@Field(2) 
	public int vkYCbCrModel() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public WGPUYCbCrVkDescriptor vkYCbCrModel(int vkYCbCrModel) {
		this.io.setIntField(this, 2, vkYCbCrModel);
		return this;
	}
	@Field(3) 
	public int vkYCbCrRange() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public WGPUYCbCrVkDescriptor vkYCbCrRange(int vkYCbCrRange) {
		this.io.setIntField(this, 3, vkYCbCrRange);
		return this;
	}
	@Field(4) 
	public int vkComponentSwizzleRed() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public WGPUYCbCrVkDescriptor vkComponentSwizzleRed(int vkComponentSwizzleRed) {
		this.io.setIntField(this, 4, vkComponentSwizzleRed);
		return this;
	}
	@Field(5) 
	public int vkComponentSwizzleGreen() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public WGPUYCbCrVkDescriptor vkComponentSwizzleGreen(int vkComponentSwizzleGreen) {
		this.io.setIntField(this, 5, vkComponentSwizzleGreen);
		return this;
	}
	@Field(6) 
	public int vkComponentSwizzleBlue() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public WGPUYCbCrVkDescriptor vkComponentSwizzleBlue(int vkComponentSwizzleBlue) {
		this.io.setIntField(this, 6, vkComponentSwizzleBlue);
		return this;
	}
	@Field(7) 
	public int vkComponentSwizzleAlpha() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public WGPUYCbCrVkDescriptor vkComponentSwizzleAlpha(int vkComponentSwizzleAlpha) {
		this.io.setIntField(this, 7, vkComponentSwizzleAlpha);
		return this;
	}
	@Field(8) 
	public int vkXChromaOffset() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public WGPUYCbCrVkDescriptor vkXChromaOffset(int vkXChromaOffset) {
		this.io.setIntField(this, 8, vkXChromaOffset);
		return this;
	}
	@Field(9) 
	public int vkYChromaOffset() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public WGPUYCbCrVkDescriptor vkYChromaOffset(int vkYChromaOffset) {
		this.io.setIntField(this, 9, vkYChromaOffset);
		return this;
	}
	/// C type : WGPUFilterMode
	@Field(10) 
	public IntValuedEnum<WGPUFilterMode > vkChromaFilter() {
		return this.io.getEnumField(this, 10);
	}
	/// C type : WGPUFilterMode
	@Field(10) 
	public WGPUYCbCrVkDescriptor vkChromaFilter(IntValuedEnum<WGPUFilterMode > vkChromaFilter) {
		this.io.setEnumField(this, 10, vkChromaFilter);
		return this;
	}
	/// C type : WGPUBool
	@Field(11) 
	public int forceExplicitReconstruction() {
		return this.io.getIntField(this, 11);
	}
	/// C type : WGPUBool
	@Field(11) 
	public WGPUYCbCrVkDescriptor forceExplicitReconstruction(int forceExplicitReconstruction) {
		this.io.setIntField(this, 11, forceExplicitReconstruction);
		return this;
	}
	@Field(12) 
	public long externalFormat() {
		return this.io.getLongField(this, 12);
	}
	@Field(12) 
	public WGPUYCbCrVkDescriptor externalFormat(long externalFormat) {
		this.io.setLongField(this, 12, externalFormat);
		return this;
	}
	public WGPUYCbCrVkDescriptor(Pointer pointer) {
		super(pointer);
	}
}
