package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUDrmFormatCapabilities extends StructObject {
	public WGPUDrmFormatCapabilities() {
		super();
	}
	/// C type : WGPUChainedStructOut
	@Field(0) 
	public WGPUChainedStructOut chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStructOut
	@Field(0) 
	public WGPUDrmFormatCapabilities chain(WGPUChainedStructOut chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Ptr 
	@Field(1) 
	public long propertiesCount() {
		return this.io.getSizeTField(this, 1);
	}
	@Ptr 
	@Field(1) 
	public WGPUDrmFormatCapabilities propertiesCount(long propertiesCount) {
		this.io.setSizeTField(this, 1, propertiesCount);
		return this;
	}
	/// C type : const WGPUDrmFormatProperties*
	@Field(2) 
	public Pointer<WGPUDrmFormatProperties > properties() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : const WGPUDrmFormatProperties*
	@Field(2) 
	public WGPUDrmFormatCapabilities properties(Pointer<WGPUDrmFormatProperties > properties) {
		this.io.setPointerField(this, 2, properties);
		return this;
	}
	public WGPUDrmFormatCapabilities(Pointer pointer) {
		super(pointer);
	}
}
