package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUCallbackMode;
import webgpu.WebgpuLibrary.WGPURequestAdapterCallback2;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPURequestAdapterCallbackInfo2 extends StructObject {
	public WGPURequestAdapterCallbackInfo2() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPURequestAdapterCallbackInfo2 nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUCallbackMode
	@Field(1) 
	public IntValuedEnum<WGPUCallbackMode > mode() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : WGPUCallbackMode
	@Field(1) 
	public WGPURequestAdapterCallbackInfo2 mode(IntValuedEnum<WGPUCallbackMode > mode) {
		this.io.setEnumField(this, 1, mode);
		return this;
	}
	/// C type : WGPURequestAdapterCallback2
	@Field(2) 
	public Pointer<WGPURequestAdapterCallback2 > callback() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : WGPURequestAdapterCallback2
	@Field(2) 
	public WGPURequestAdapterCallbackInfo2 callback(Pointer<WGPURequestAdapterCallback2 > callback) {
		this.io.setPointerField(this, 2, callback);
		return this;
	}
	/// C type : void*
	@Field(3) 
	public Pointer<? > userdata1() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : void*
	@Field(3) 
	public WGPURequestAdapterCallbackInfo2 userdata1(Pointer<? > userdata1) {
		this.io.setPointerField(this, 3, userdata1);
		return this;
	}
	/// C type : void*
	@Field(4) 
	public Pointer<? > userdata2() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : void*
	@Field(4) 
	public WGPURequestAdapterCallbackInfo2 userdata2(Pointer<? > userdata2) {
		this.io.setPointerField(this, 4, userdata2);
		return this;
	}
	public WGPURequestAdapterCallbackInfo2(Pointer pointer) {
		super(pointer);
	}
}
