package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPURenderPassDescriptorExpandResolveRect extends StructObject {
	public WGPURenderPassDescriptorExpandResolveRect() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPURenderPassDescriptorExpandResolveRect chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Field(1) 
	public int x() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPURenderPassDescriptorExpandResolveRect x(int x) {
		this.io.setIntField(this, 1, x);
		return this;
	}
	@Field(2) 
	public int y() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public WGPURenderPassDescriptorExpandResolveRect y(int y) {
		this.io.setIntField(this, 2, y);
		return this;
	}
	@Field(3) 
	public int width() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public WGPURenderPassDescriptorExpandResolveRect width(int width) {
		this.io.setIntField(this, 3, width);
		return this;
	}
	@Field(4) 
	public int height() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public WGPURenderPassDescriptorExpandResolveRect height(int height) {
		this.io.setIntField(this, 4, height);
		return this;
	}
	public WGPURenderPassDescriptorExpandResolveRect(Pointer pointer) {
		super(pointer);
	}
}
