package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUCullMode;
import webgpu.WebgpuLibrary.WGPUFrontFace;
import webgpu.WebgpuLibrary.WGPUIndexFormat;
import webgpu.WebgpuLibrary.WGPUPrimitiveTopology;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUPrimitiveState extends StructObject {
	public WGPUPrimitiveState() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUPrimitiveState nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUPrimitiveTopology
	@Field(1) 
	public IntValuedEnum<WGPUPrimitiveTopology > topology() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : WGPUPrimitiveTopology
	@Field(1) 
	public WGPUPrimitiveState topology(IntValuedEnum<WGPUPrimitiveTopology > topology) {
		this.io.setEnumField(this, 1, topology);
		return this;
	}
	/// C type : WGPUIndexFormat
	@Field(2) 
	public IntValuedEnum<WGPUIndexFormat > stripIndexFormat() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : WGPUIndexFormat
	@Field(2) 
	public WGPUPrimitiveState stripIndexFormat(IntValuedEnum<WGPUIndexFormat > stripIndexFormat) {
		this.io.setEnumField(this, 2, stripIndexFormat);
		return this;
	}
	/// C type : WGPUFrontFace
	@Field(3) 
	public IntValuedEnum<WGPUFrontFace > frontFace() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : WGPUFrontFace
	@Field(3) 
	public WGPUPrimitiveState frontFace(IntValuedEnum<WGPUFrontFace > frontFace) {
		this.io.setEnumField(this, 3, frontFace);
		return this;
	}
	/// C type : WGPUCullMode
	@Field(4) 
	public IntValuedEnum<WGPUCullMode > cullMode() {
		return this.io.getEnumField(this, 4);
	}
	/// C type : WGPUCullMode
	@Field(4) 
	public WGPUPrimitiveState cullMode(IntValuedEnum<WGPUCullMode > cullMode) {
		this.io.setEnumField(this, 4, cullMode);
		return this;
	}
	/// C type : WGPUBool
	@Field(5) 
	public int unclippedDepth() {
		return this.io.getIntField(this, 5);
	}
	/// C type : WGPUBool
	@Field(5) 
	public WGPUPrimitiveState unclippedDepth(int unclippedDepth) {
		this.io.setIntField(this, 5, unclippedDepth);
		return this;
	}
	public WGPUPrimitiveState(Pointer pointer) {
		super(pointer);
	}
}
