package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUPresentMode;
import webgpu.WebgpuLibrary.WGPUTextureFormat;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSwapChainDescriptor extends StructObject {
	public WGPUSwapChainDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUSwapChainDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > label() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPUSwapChainDescriptor label(Pointer<Byte > label) {
		this.io.setPointerField(this, 1, label);
		return this;
	}
	/// C type : WGPUTextureUsage
	@Field(2) 
	public long usage() {
		return this.io.getLongField(this, 2);
	}
	/// C type : WGPUTextureUsage
	@Field(2) 
	public WGPUSwapChainDescriptor usage(long usage) {
		this.io.setLongField(this, 2, usage);
		return this;
	}
	/// C type : WGPUTextureFormat
	@Field(3) 
	public IntValuedEnum<WGPUTextureFormat > format() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : WGPUTextureFormat
	@Field(3) 
	public WGPUSwapChainDescriptor format(IntValuedEnum<WGPUTextureFormat > format) {
		this.io.setEnumField(this, 3, format);
		return this;
	}
	@Field(4) 
	public int width() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public WGPUSwapChainDescriptor width(int width) {
		this.io.setIntField(this, 4, width);
		return this;
	}
	@Field(5) 
	public int height() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public WGPUSwapChainDescriptor height(int height) {
		this.io.setIntField(this, 5, height);
		return this;
	}
	/// C type : WGPUPresentMode
	@Field(6) 
	public IntValuedEnum<WGPUPresentMode > presentMode() {
		return this.io.getEnumField(this, 6);
	}
	/// C type : WGPUPresentMode
	@Field(6) 
	public WGPUSwapChainDescriptor presentMode(IntValuedEnum<WGPUPresentMode > presentMode) {
		this.io.setEnumField(this, 6, presentMode);
		return this;
	}
	public WGPUSwapChainDescriptor(Pointer pointer) {
		super(pointer);
	}
}
