package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUTextureAspect;
import webgpu.WebgpuLibrary.WGPUTextureFormat;
import webgpu.WebgpuLibrary.WGPUTextureViewDimension;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUTextureViewDescriptor extends StructObject {
	public WGPUTextureViewDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUTextureViewDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > label() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPUTextureViewDescriptor label(Pointer<Byte > label) {
		this.io.setPointerField(this, 1, label);
		return this;
	}
	/// C type : WGPUTextureFormat
	@Field(2) 
	public IntValuedEnum<WGPUTextureFormat > format() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : WGPUTextureFormat
	@Field(2) 
	public WGPUTextureViewDescriptor format(IntValuedEnum<WGPUTextureFormat > format) {
		this.io.setEnumField(this, 2, format);
		return this;
	}
	/// C type : WGPUTextureViewDimension
	@Field(3) 
	public IntValuedEnum<WGPUTextureViewDimension > dimension() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : WGPUTextureViewDimension
	@Field(3) 
	public WGPUTextureViewDescriptor dimension(IntValuedEnum<WGPUTextureViewDimension > dimension) {
		this.io.setEnumField(this, 3, dimension);
		return this;
	}
	@Field(4) 
	public int baseMipLevel() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public WGPUTextureViewDescriptor baseMipLevel(int baseMipLevel) {
		this.io.setIntField(this, 4, baseMipLevel);
		return this;
	}
	@Field(5) 
	public int mipLevelCount() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public WGPUTextureViewDescriptor mipLevelCount(int mipLevelCount) {
		this.io.setIntField(this, 5, mipLevelCount);
		return this;
	}
	@Field(6) 
	public int baseArrayLayer() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public WGPUTextureViewDescriptor baseArrayLayer(int baseArrayLayer) {
		this.io.setIntField(this, 6, baseArrayLayer);
		return this;
	}
	@Field(7) 
	public int arrayLayerCount() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public WGPUTextureViewDescriptor arrayLayerCount(int arrayLayerCount) {
		this.io.setIntField(this, 7, arrayLayerCount);
		return this;
	}
	/// C type : WGPUTextureAspect
	@Field(8) 
	public IntValuedEnum<WGPUTextureAspect > aspect() {
		return this.io.getEnumField(this, 8);
	}
	/// C type : WGPUTextureAspect
	@Field(8) 
	public WGPUTextureViewDescriptor aspect(IntValuedEnum<WGPUTextureAspect > aspect) {
		this.io.setEnumField(this, 8, aspect);
		return this;
	}
	public WGPUTextureViewDescriptor(Pointer pointer) {
		super(pointer);
	}
}
