package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import webgpu.WebgpuLibrary.WGPUSharedFence;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSharedTextureMemoryBeginAccessDescriptor extends StructObject {
	public WGPUSharedTextureMemoryBeginAccessDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUSharedTextureMemoryBeginAccessDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUBool
	@Field(1) 
	public int concurrentRead() {
		return this.io.getIntField(this, 1);
	}
	/// C type : WGPUBool
	@Field(1) 
	public WGPUSharedTextureMemoryBeginAccessDescriptor concurrentRead(int concurrentRead) {
		this.io.setIntField(this, 1, concurrentRead);
		return this;
	}
	/// C type : WGPUBool
	@Field(2) 
	public int initialized() {
		return this.io.getIntField(this, 2);
	}
	/// C type : WGPUBool
	@Field(2) 
	public WGPUSharedTextureMemoryBeginAccessDescriptor initialized(int initialized) {
		this.io.setIntField(this, 2, initialized);
		return this;
	}
	@Ptr 
	@Field(3) 
	public long fenceCount() {
		return this.io.getSizeTField(this, 3);
	}
	@Ptr 
	@Field(3) 
	public WGPUSharedTextureMemoryBeginAccessDescriptor fenceCount(long fenceCount) {
		this.io.setSizeTField(this, 3, fenceCount);
		return this;
	}
	/// C type : const WGPUSharedFence*
	@Field(4) 
	public Pointer<WGPUSharedFence > fences() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : const WGPUSharedFence*
	@Field(4) 
	public WGPUSharedTextureMemoryBeginAccessDescriptor fences(Pointer<WGPUSharedFence > fences) {
		this.io.setPointerField(this, 4, fences);
		return this;
	}
	/// C type : const uint64_t*
	@Field(5) 
	public Pointer<Long > signaledValues() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : const uint64_t*
	@Field(5) 
	public WGPUSharedTextureMemoryBeginAccessDescriptor signaledValues(Pointer<Long > signaledValues) {
		this.io.setPointerField(this, 5, signaledValues);
		return this;
	}
	public WGPUSharedTextureMemoryBeginAccessDescriptor(Pointer pointer) {
		super(pointer);
	}
}
