package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import webgpu.WebgpuLibrary.WGPUBindGroupLayout;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUBindGroupDescriptor extends StructObject {
	public WGPUBindGroupDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUBindGroupDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > label() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPUBindGroupDescriptor label(Pointer<Byte > label) {
		this.io.setPointerField(this, 1, label);
		return this;
	}
	/// C type : WGPUBindGroupLayout
	@Field(2) 
	public WGPUBindGroupLayout layout() {
		return this.io.getTypedPointerField(this, 2);
	}
	/// C type : WGPUBindGroupLayout
	@Field(2) 
	public WGPUBindGroupDescriptor layout(WGPUBindGroupLayout layout) {
		this.io.setPointerField(this, 2, layout);
		return this;
	}
	@Ptr 
	@Field(3) 
	public long entryCount() {
		return this.io.getSizeTField(this, 3);
	}
	@Ptr 
	@Field(3) 
	public WGPUBindGroupDescriptor entryCount(long entryCount) {
		this.io.setSizeTField(this, 3, entryCount);
		return this;
	}
	/// C type : const WGPUBindGroupEntry*
	@Field(4) 
	public Pointer<WGPUBindGroupEntry > entries() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : const WGPUBindGroupEntry*
	@Field(4) 
	public WGPUBindGroupDescriptor entries(Pointer<WGPUBindGroupEntry > entries) {
		this.io.setPointerField(this, 4, entries);
		return this;
	}
	public WGPUBindGroupDescriptor(Pointer pointer) {
		super(pointer);
	}
}
