package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUVertexFormat;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUVertexAttribute extends StructObject {
	public WGPUVertexAttribute() {
		super();
	}
	/// C type : WGPUVertexFormat
	@Field(0) 
	public IntValuedEnum<WGPUVertexFormat > format() {
		return this.io.getEnumField(this, 0);
	}
	/// C type : WGPUVertexFormat
	@Field(0) 
	public WGPUVertexAttribute format(IntValuedEnum<WGPUVertexFormat > format) {
		this.io.setEnumField(this, 0, format);
		return this;
	}
	@Field(1) 
	public long offset() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public WGPUVertexAttribute offset(long offset) {
		this.io.setLongField(this, 1, offset);
		return this;
	}
	@Field(2) 
	public int shaderLocation() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public WGPUVertexAttribute shaderLocation(int shaderLocation) {
		this.io.setIntField(this, 2, shaderLocation);
		return this;
	}
	public WGPUVertexAttribute(Pointer pointer) {
		super(pointer);
	}
}
