package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUDawnRenderPassColorAttachmentRenderToSingleSampled extends StructObject {
	public WGPUDawnRenderPassColorAttachmentRenderToSingleSampled() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUDawnRenderPassColorAttachmentRenderToSingleSampled chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Field(1) 
	public int implicitSampleCount() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUDawnRenderPassColorAttachmentRenderToSingleSampled implicitSampleCount(int implicitSampleCount) {
		this.io.setIntField(this, 1, implicitSampleCount);
		return this;
	}
	public WGPUDawnRenderPassColorAttachmentRenderToSingleSampled(Pointer pointer) {
		super(pointer);
	}
}
