package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUTextureFormat;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSharedTextureMemoryProperties extends StructObject {
	public WGPUSharedTextureMemoryProperties() {
		super();
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public Pointer<WGPUChainedStructOut > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public WGPUSharedTextureMemoryProperties nextInChain(Pointer<WGPUChainedStructOut > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUTextureUsage
	@Field(1) 
	public long usage() {
		return this.io.getLongField(this, 1);
	}
	/// C type : WGPUTextureUsage
	@Field(1) 
	public WGPUSharedTextureMemoryProperties usage(long usage) {
		this.io.setLongField(this, 1, usage);
		return this;
	}
	/// C type : WGPUExtent3D
	@Field(2) 
	public WGPUExtent3D size() {
		return this.io.getNativeObjectField(this, 2);
	}
	/// C type : WGPUExtent3D
	@Field(2) 
	public WGPUSharedTextureMemoryProperties size(WGPUExtent3D size) {
		this.io.setNativeObjectField(this, 2, size);
		return this;
	}
	/// C type : WGPUTextureFormat
	@Field(3) 
	public IntValuedEnum<WGPUTextureFormat > format() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : WGPUTextureFormat
	@Field(3) 
	public WGPUSharedTextureMemoryProperties format(IntValuedEnum<WGPUTextureFormat > format) {
		this.io.setEnumField(this, 3, format);
		return this;
	}
	public WGPUSharedTextureMemoryProperties(Pointer pointer) {
		super(pointer);
	}
}
