package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import webgpu.WebgpuLibrary.WGPUCompositeAlphaMode;
import webgpu.WebgpuLibrary.WGPUPresentMode;
import webgpu.WebgpuLibrary.WGPUTextureFormat;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSurfaceCapabilities extends StructObject {
	public WGPUSurfaceCapabilities() {
		super();
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public Pointer<WGPUChainedStructOut > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public WGPUSurfaceCapabilities nextInChain(Pointer<WGPUChainedStructOut > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUTextureUsage
	@Field(1) 
	public long usages() {
		return this.io.getLongField(this, 1);
	}
	/// C type : WGPUTextureUsage
	@Field(1) 
	public WGPUSurfaceCapabilities usages(long usages) {
		this.io.setLongField(this, 1, usages);
		return this;
	}
	@Ptr 
	@Field(2) 
	public long formatCount() {
		return this.io.getSizeTField(this, 2);
	}
	@Ptr 
	@Field(2) 
	public WGPUSurfaceCapabilities formatCount(long formatCount) {
		this.io.setSizeTField(this, 2, formatCount);
		return this;
	}
	/// C type : const WGPUTextureFormat*
	@Field(3) 
	public Pointer<IntValuedEnum<WGPUTextureFormat > > formats() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : const WGPUTextureFormat*
	@Field(3) 
	public WGPUSurfaceCapabilities formats(Pointer<IntValuedEnum<WGPUTextureFormat > > formats) {
		this.io.setPointerField(this, 3, formats);
		return this;
	}
	@Ptr 
	@Field(4) 
	public long presentModeCount() {
		return this.io.getSizeTField(this, 4);
	}
	@Ptr 
	@Field(4) 
	public WGPUSurfaceCapabilities presentModeCount(long presentModeCount) {
		this.io.setSizeTField(this, 4, presentModeCount);
		return this;
	}
	/// C type : const WGPUPresentMode*
	@Field(5) 
	public Pointer<IntValuedEnum<WGPUPresentMode > > presentModes() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : const WGPUPresentMode*
	@Field(5) 
	public WGPUSurfaceCapabilities presentModes(Pointer<IntValuedEnum<WGPUPresentMode > > presentModes) {
		this.io.setPointerField(this, 5, presentModes);
		return this;
	}
	@Ptr 
	@Field(6) 
	public long alphaModeCount() {
		return this.io.getSizeTField(this, 6);
	}
	@Ptr 
	@Field(6) 
	public WGPUSurfaceCapabilities alphaModeCount(long alphaModeCount) {
		this.io.setSizeTField(this, 6, alphaModeCount);
		return this;
	}
	/// C type : const WGPUCompositeAlphaMode*
	@Field(7) 
	public Pointer<IntValuedEnum<WGPUCompositeAlphaMode > > alphaModes() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : const WGPUCompositeAlphaMode*
	@Field(7) 
	public WGPUSurfaceCapabilities alphaModes(Pointer<IntValuedEnum<WGPUCompositeAlphaMode > > alphaModes) {
		this.io.setPointerField(this, 7, alphaModes);
		return this;
	}
	public WGPUSurfaceCapabilities(Pointer pointer) {
		super(pointer);
	}
}
