package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSharedTextureMemoryDmaBufPlane extends StructObject {
	public WGPUSharedTextureMemoryDmaBufPlane() {
		super();
	}
	@Field(0) 
	public int fd() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public WGPUSharedTextureMemoryDmaBufPlane fd(int fd) {
		this.io.setIntField(this, 0, fd);
		return this;
	}
	@Field(1) 
	public long offset() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public WGPUSharedTextureMemoryDmaBufPlane offset(long offset) {
		this.io.setLongField(this, 1, offset);
		return this;
	}
	@Field(2) 
	public int stride() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public WGPUSharedTextureMemoryDmaBufPlane stride(int stride) {
		this.io.setIntField(this, 2, stride);
		return this;
	}
	public WGPUSharedTextureMemoryDmaBufPlane(Pointer pointer) {
		super(pointer);
	}
}
