package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUSurfaceGetCurrentTextureStatus;
import webgpu.WebgpuLibrary.WGPUTexture;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUSurfaceTexture extends StructObject {
	public WGPUSurfaceTexture() {
		super();
	}
	/// C type : WGPUTexture
	@Field(0) 
	public WGPUTexture texture() {
		return this.io.getTypedPointerField(this, 0);
	}
	/// C type : WGPUTexture
	@Field(0) 
	public WGPUSurfaceTexture texture(WGPUTexture texture) {
		this.io.setPointerField(this, 0, texture);
		return this;
	}
	/// C type : WGPUBool
	@Field(1) 
	public int suboptimal() {
		return this.io.getIntField(this, 1);
	}
	/// C type : WGPUBool
	@Field(1) 
	public WGPUSurfaceTexture suboptimal(int suboptimal) {
		this.io.setIntField(this, 1, suboptimal);
		return this;
	}
	/// C type : WGPUSurfaceGetCurrentTextureStatus
	@Field(2) 
	public IntValuedEnum<WGPUSurfaceGetCurrentTextureStatus > status() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : WGPUSurfaceGetCurrentTextureStatus
	@Field(2) 
	public WGPUSurfaceTexture status(IntValuedEnum<WGPUSurfaceGetCurrentTextureStatus > status) {
		this.io.setEnumField(this, 2, status);
		return this;
	}
	public WGPUSurfaceTexture(Pointer pointer) {
		super(pointer);
	}
}
