package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUDrmFormatProperties extends StructObject {
	public WGPUDrmFormatProperties() {
		super();
	}
	@Field(0) 
	public long modifier() {
		return this.io.getLongField(this, 0);
	}
	@Field(0) 
	public WGPUDrmFormatProperties modifier(long modifier) {
		this.io.setLongField(this, 0, modifier);
		return this;
	}
	@Field(1) 
	public int modifierPlaneCount() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUDrmFormatProperties modifierPlaneCount(int modifierPlaneCount) {
		this.io.setIntField(this, 1, modifierPlaneCount);
		return this;
	}
	public WGPUDrmFormatProperties(Pointer pointer) {
		super(pointer);
	}
}
