package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUDawnTogglesDescriptor extends StructObject {
	public WGPUDawnTogglesDescriptor() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUDawnTogglesDescriptor chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Ptr 
	@Field(1) 
	public long enabledToggleCount() {
		return this.io.getSizeTField(this, 1);
	}
	@Ptr 
	@Field(1) 
	public WGPUDawnTogglesDescriptor enabledToggleCount(long enabledToggleCount) {
		this.io.setSizeTField(this, 1, enabledToggleCount);
		return this;
	}
	/// C type : const char**
	@Field(2) 
	public Pointer<Pointer<Byte > > enabledToggles() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : const char**
	@Field(2) 
	public WGPUDawnTogglesDescriptor enabledToggles(Pointer<Pointer<Byte > > enabledToggles) {
		this.io.setPointerField(this, 2, enabledToggles);
		return this;
	}
	@Ptr 
	@Field(3) 
	public long disabledToggleCount() {
		return this.io.getSizeTField(this, 3);
	}
	@Ptr 
	@Field(3) 
	public WGPUDawnTogglesDescriptor disabledToggleCount(long disabledToggleCount) {
		this.io.setSizeTField(this, 3, disabledToggleCount);
		return this;
	}
	/// C type : const char**
	@Field(4) 
	public Pointer<Pointer<Byte > > disabledToggles() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : const char**
	@Field(4) 
	public WGPUDawnTogglesDescriptor disabledToggles(Pointer<Pointer<Byte > > disabledToggles) {
		this.io.setPointerField(this, 4, disabledToggles);
		return this;
	}
	public WGPUDawnTogglesDescriptor(Pointer pointer) {
		super(pointer);
	}
}
