package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUExternalTexture;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUExternalTextureBindingEntry extends StructObject {
	public WGPUExternalTextureBindingEntry() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUExternalTextureBindingEntry chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : WGPUExternalTexture
	@Field(1) 
	public WGPUExternalTexture externalTexture() {
		return this.io.getTypedPointerField(this, 1);
	}
	/// C type : WGPUExternalTexture
	@Field(1) 
	public WGPUExternalTextureBindingEntry externalTexture(WGPUExternalTexture externalTexture) {
		this.io.setPointerField(this, 1, externalTexture);
		return this;
	}
	public WGPUExternalTextureBindingEntry(Pointer pointer) {
		super(pointer);
	}
}
