package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUDawnWireWGSLControl extends StructObject {
	public WGPUDawnWireWGSLControl() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUDawnWireWGSLControl chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : WGPUBool
	@Field(1) 
	public int enableExperimental() {
		return this.io.getIntField(this, 1);
	}
	/// C type : WGPUBool
	@Field(1) 
	public WGPUDawnWireWGSLControl enableExperimental(int enableExperimental) {
		this.io.setIntField(this, 1, enableExperimental);
		return this;
	}
	/// C type : WGPUBool
	@Field(2) 
	public int enableUnsafe() {
		return this.io.getIntField(this, 2);
	}
	/// C type : WGPUBool
	@Field(2) 
	public WGPUDawnWireWGSLControl enableUnsafe(int enableUnsafe) {
		this.io.setIntField(this, 2, enableUnsafe);
		return this;
	}
	/// C type : WGPUBool
	@Field(3) 
	public int enableTesting() {
		return this.io.getIntField(this, 3);
	}
	/// C type : WGPUBool
	@Field(3) 
	public WGPUDawnWireWGSLControl enableTesting(int enableTesting) {
		this.io.setIntField(this, 3, enableTesting);
		return this;
	}
	public WGPUDawnWireWGSLControl(Pointer pointer) {
		super(pointer);
	}
}
