package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUInstanceDescriptor extends StructObject {
	public WGPUInstanceDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUInstanceDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUInstanceFeatures
	@Field(1) 
	public WGPUInstanceFeatures features() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : WGPUInstanceFeatures
	@Field(1) 
	public WGPUInstanceDescriptor features(WGPUInstanceFeatures features) {
		this.io.setNativeObjectField(this, 1, features);
		return this;
	}
	public WGPUInstanceDescriptor(Pointer pointer) {
		super(pointer);
	}
}
