package webgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUTextureFormat;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUPipelineLayoutStorageAttachment extends StructObject {
	public WGPUPipelineLayoutStorageAttachment() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUPipelineLayoutStorageAttachment nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	@Field(1) 
	public long offset() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public WGPUPipelineLayoutStorageAttachment offset(long offset) {
		this.io.setLongField(this, 1, offset);
		return this;
	}
	/// C type : WGPUTextureFormat
	@Field(2) 
	public IntValuedEnum<WGPUTextureFormat > format() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : WGPUTextureFormat
	@Field(2) 
	public WGPUPipelineLayoutStorageAttachment format(IntValuedEnum<WGPUTextureFormat > format) {
		this.io.setEnumField(this, 2, format);
		return this;
	}
	public WGPUPipelineLayoutStorageAttachment(Pointer pointer) {
		super(pointer);
	}
}
