package webgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import webgpu.WebgpuLibrary.WGPUCallback;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("webgpu") 
public class WGPUBufferHostMappedPointer extends StructObject {
	public WGPUBufferHostMappedPointer() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUBufferHostMappedPointer chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : void*
	@Field(1) 
	public Pointer<? > pointer() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : void*
	@Field(1) 
	public WGPUBufferHostMappedPointer pointer(Pointer<? > pointer) {
		this.io.setPointerField(this, 1, pointer);
		return this;
	}
	/// C type : WGPUCallback
	@Field(2) 
	public Pointer<WGPUCallback > disposeCallback() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : WGPUCallback
	@Field(2) 
	public WGPUBufferHostMappedPointer disposeCallback(Pointer<WGPUCallback > disposeCallback) {
		this.io.setPointerField(this, 2, disposeCallback);
		return this;
	}
	/// C type : void*
	@Field(3) 
	public Pointer<? > userdata() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : void*
	@Field(3) 
	public WGPUBufferHostMappedPointer userdata(Pointer<? > userdata) {
		this.io.setPointerField(this, 3, userdata);
		return this;
	}
	public WGPUBufferHostMappedPointer(Pointer pointer) {
		super(pointer);
	}
}
