package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUQueue;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUWrappedSubmissionIndex extends StructObject {
	public WGPUWrappedSubmissionIndex() {
		super();
	}
	/// C type : WGPUQueue
	@Field(0) 
	public WGPUQueue queue() {
		return this.io.getTypedPointerField(this, 0);
	}
	/// C type : WGPUQueue
	@Field(0) 
	public WGPUWrappedSubmissionIndex queue(WGPUQueue queue) {
		this.io.setPointerField(this, 0, queue);
		return this;
	}
	/// C type : WGPUSubmissionIndex
	@Field(1) 
	public long submissionIndex() {
		return this.io.getLongField(this, 1);
	}
	/// C type : WGPUSubmissionIndex
	@Field(1) 
	public WGPUWrappedSubmissionIndex submissionIndex(long submissionIndex) {
		this.io.setLongField(this, 1, submissionIndex);
		return this;
	}
	public WGPUWrappedSubmissionIndex(Pointer pointer) {
		super(pointer);
	}
}
