package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUHubReport extends StructObject {
	public WGPUHubReport() {
		super();
	}
	/// C type : WGPURegistryReport
	@Field(0) 
	public WGPURegistryReport adapters() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPURegistryReport
	@Field(0) 
	public WGPUHubReport adapters(WGPURegistryReport adapters) {
		this.io.setNativeObjectField(this, 0, adapters);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(1) 
	public WGPURegistryReport devices() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : WGPURegistryReport
	@Field(1) 
	public WGPUHubReport devices(WGPURegistryReport devices) {
		this.io.setNativeObjectField(this, 1, devices);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(2) 
	public WGPURegistryReport queues() {
		return this.io.getNativeObjectField(this, 2);
	}
	/// C type : WGPURegistryReport
	@Field(2) 
	public WGPUHubReport queues(WGPURegistryReport queues) {
		this.io.setNativeObjectField(this, 2, queues);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(3) 
	public WGPURegistryReport pipelineLayouts() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : WGPURegistryReport
	@Field(3) 
	public WGPUHubReport pipelineLayouts(WGPURegistryReport pipelineLayouts) {
		this.io.setNativeObjectField(this, 3, pipelineLayouts);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(4) 
	public WGPURegistryReport shaderModules() {
		return this.io.getNativeObjectField(this, 4);
	}
	/// C type : WGPURegistryReport
	@Field(4) 
	public WGPUHubReport shaderModules(WGPURegistryReport shaderModules) {
		this.io.setNativeObjectField(this, 4, shaderModules);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(5) 
	public WGPURegistryReport bindGroupLayouts() {
		return this.io.getNativeObjectField(this, 5);
	}
	/// C type : WGPURegistryReport
	@Field(5) 
	public WGPUHubReport bindGroupLayouts(WGPURegistryReport bindGroupLayouts) {
		this.io.setNativeObjectField(this, 5, bindGroupLayouts);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(6) 
	public WGPURegistryReport bindGroups() {
		return this.io.getNativeObjectField(this, 6);
	}
	/// C type : WGPURegistryReport
	@Field(6) 
	public WGPUHubReport bindGroups(WGPURegistryReport bindGroups) {
		this.io.setNativeObjectField(this, 6, bindGroups);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(7) 
	public WGPURegistryReport commandBuffers() {
		return this.io.getNativeObjectField(this, 7);
	}
	/// C type : WGPURegistryReport
	@Field(7) 
	public WGPUHubReport commandBuffers(WGPURegistryReport commandBuffers) {
		this.io.setNativeObjectField(this, 7, commandBuffers);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(8) 
	public WGPURegistryReport renderBundles() {
		return this.io.getNativeObjectField(this, 8);
	}
	/// C type : WGPURegistryReport
	@Field(8) 
	public WGPUHubReport renderBundles(WGPURegistryReport renderBundles) {
		this.io.setNativeObjectField(this, 8, renderBundles);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(9) 
	public WGPURegistryReport renderPipelines() {
		return this.io.getNativeObjectField(this, 9);
	}
	/// C type : WGPURegistryReport
	@Field(9) 
	public WGPUHubReport renderPipelines(WGPURegistryReport renderPipelines) {
		this.io.setNativeObjectField(this, 9, renderPipelines);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(10) 
	public WGPURegistryReport computePipelines() {
		return this.io.getNativeObjectField(this, 10);
	}
	/// C type : WGPURegistryReport
	@Field(10) 
	public WGPUHubReport computePipelines(WGPURegistryReport computePipelines) {
		this.io.setNativeObjectField(this, 10, computePipelines);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(11) 
	public WGPURegistryReport querySets() {
		return this.io.getNativeObjectField(this, 11);
	}
	/// C type : WGPURegistryReport
	@Field(11) 
	public WGPUHubReport querySets(WGPURegistryReport querySets) {
		this.io.setNativeObjectField(this, 11, querySets);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(12) 
	public WGPURegistryReport buffers() {
		return this.io.getNativeObjectField(this, 12);
	}
	/// C type : WGPURegistryReport
	@Field(12) 
	public WGPUHubReport buffers(WGPURegistryReport buffers) {
		this.io.setNativeObjectField(this, 12, buffers);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(13) 
	public WGPURegistryReport textures() {
		return this.io.getNativeObjectField(this, 13);
	}
	/// C type : WGPURegistryReport
	@Field(13) 
	public WGPUHubReport textures(WGPURegistryReport textures) {
		this.io.setNativeObjectField(this, 13, textures);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(14) 
	public WGPURegistryReport textureViews() {
		return this.io.getNativeObjectField(this, 14);
	}
	/// C type : WGPURegistryReport
	@Field(14) 
	public WGPUHubReport textureViews(WGPURegistryReport textureViews) {
		this.io.setNativeObjectField(this, 14, textureViews);
		return this;
	}
	/// C type : WGPURegistryReport
	@Field(15) 
	public WGPURegistryReport samplers() {
		return this.io.getNativeObjectField(this, 15);
	}
	/// C type : WGPURegistryReport
	@Field(15) 
	public WGPUHubReport samplers(WGPURegistryReport samplers) {
		this.io.setNativeObjectField(this, 15, samplers);
		return this;
	}
	public WGPUHubReport(Pointer pointer) {
		super(pointer);
	}
}
