package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPURegistryReport extends StructObject {
	public WGPURegistryReport() {
		super();
	}
	@Ptr 
	@Field(0) 
	public long numAllocated() {
		return this.io.getSizeTField(this, 0);
	}
	@Ptr 
	@Field(0) 
	public WGPURegistryReport numAllocated(long numAllocated) {
		this.io.setSizeTField(this, 0, numAllocated);
		return this;
	}
	@Ptr 
	@Field(1) 
	public long numKeptFromUser() {
		return this.io.getSizeTField(this, 1);
	}
	@Ptr 
	@Field(1) 
	public WGPURegistryReport numKeptFromUser(long numKeptFromUser) {
		this.io.setSizeTField(this, 1, numKeptFromUser);
		return this;
	}
	@Ptr 
	@Field(2) 
	public long numReleasedFromUser() {
		return this.io.getSizeTField(this, 2);
	}
	@Ptr 
	@Field(2) 
	public WGPURegistryReport numReleasedFromUser(long numReleasedFromUser) {
		this.io.setSizeTField(this, 2, numReleasedFromUser);
		return this;
	}
	@Ptr 
	@Field(3) 
	public long numError() {
		return this.io.getSizeTField(this, 3);
	}
	@Ptr 
	@Field(3) 
	public WGPURegistryReport numError(long numError) {
		this.io.setSizeTField(this, 3, numError);
		return this;
	}
	@Ptr 
	@Field(4) 
	public long elementSize() {
		return this.io.getSizeTField(this, 4);
	}
	@Ptr 
	@Field(4) 
	public WGPURegistryReport elementSize(long elementSize) {
		this.io.setSizeTField(this, 4, elementSize);
		return this;
	}
	public WGPURegistryReport(Pointer pointer) {
		super(pointer);
	}
}
