package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUDx12Compiler;
import wgpu.WgpuLibrary.WGPUGles3MinorVersion;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUInstanceExtras extends StructObject {
	public WGPUInstanceExtras() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUInstanceExtras chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : WGPUInstanceBackendFlags
	@Field(1) 
	public int backends() {
		return this.io.getIntField(this, 1);
	}
	/// C type : WGPUInstanceBackendFlags
	@Field(1) 
	public WGPUInstanceExtras backends(int backends) {
		this.io.setIntField(this, 1, backends);
		return this;
	}
	/// C type : WGPUInstanceFlags
	@Field(2) 
	public int flags() {
		return this.io.getIntField(this, 2);
	}
	/// C type : WGPUInstanceFlags
	@Field(2) 
	public WGPUInstanceExtras flags(int flags) {
		this.io.setIntField(this, 2, flags);
		return this;
	}
	/// C type : WGPUDx12Compiler
	@Field(3) 
	public IntValuedEnum<WGPUDx12Compiler > dx12ShaderCompiler() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : WGPUDx12Compiler
	@Field(3) 
	public WGPUInstanceExtras dx12ShaderCompiler(IntValuedEnum<WGPUDx12Compiler > dx12ShaderCompiler) {
		this.io.setEnumField(this, 3, dx12ShaderCompiler);
		return this;
	}
	/// C type : WGPUGles3MinorVersion
	@Field(4) 
	public IntValuedEnum<WGPUGles3MinorVersion > gles3MinorVersion() {
		return this.io.getEnumField(this, 4);
	}
	/// C type : WGPUGles3MinorVersion
	@Field(4) 
	public WGPUInstanceExtras gles3MinorVersion(IntValuedEnum<WGPUGles3MinorVersion > gles3MinorVersion) {
		this.io.setEnumField(this, 4, gles3MinorVersion);
		return this;
	}
	/// C type : const char*
	@Field(5) 
	public Pointer<Byte > dxilPath() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : const char*
	@Field(5) 
	public WGPUInstanceExtras dxilPath(Pointer<Byte > dxilPath) {
		this.io.setPointerField(this, 5, dxilPath);
		return this;
	}
	/// C type : const char*
	@Field(6) 
	public Pointer<Byte > dxcPath() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : const char*
	@Field(6) 
	public WGPUInstanceExtras dxcPath(Pointer<Byte > dxcPath) {
		this.io.setPointerField(this, 6, dxcPath);
		return this;
	}
	public WGPUInstanceExtras(Pointer pointer) {
		super(pointer);
	}
}
