package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUBuffer;
import wgpu.WgpuLibrary.WGPUSampler;
import wgpu.WgpuLibrary.WGPUTextureView;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUBindGroupEntry extends StructObject {
	public WGPUBindGroupEntry() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUBindGroupEntry nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	@Field(1) 
	public int binding() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUBindGroupEntry binding(int binding) {
		this.io.setIntField(this, 1, binding);
		return this;
	}
	/// C type : WGPUBuffer
	@Field(2) 
	public WGPUBuffer buffer() {
		return this.io.getTypedPointerField(this, 2);
	}
	/// C type : WGPUBuffer
	@Field(2) 
	public WGPUBindGroupEntry buffer(WGPUBuffer buffer) {
		this.io.setPointerField(this, 2, buffer);
		return this;
	}
	@Field(3) 
	public long offset() {
		return this.io.getLongField(this, 3);
	}
	@Field(3) 
	public WGPUBindGroupEntry offset(long offset) {
		this.io.setLongField(this, 3, offset);
		return this;
	}
	@Field(4) 
	public long size() {
		return this.io.getLongField(this, 4);
	}
	@Field(4) 
	public WGPUBindGroupEntry size(long size) {
		this.io.setLongField(this, 4, size);
		return this;
	}
	/// C type : WGPUSampler
	@Field(5) 
	public WGPUSampler sampler() {
		return this.io.getTypedPointerField(this, 5);
	}
	/// C type : WGPUSampler
	@Field(5) 
	public WGPUBindGroupEntry sampler(WGPUSampler sampler) {
		this.io.setPointerField(this, 5, sampler);
		return this;
	}
	/// C type : WGPUTextureView
	@Field(6) 
	public WGPUTextureView textureView() {
		return this.io.getTypedPointerField(this, 6);
	}
	/// C type : WGPUTextureView
	@Field(6) 
	public WGPUBindGroupEntry textureView(WGPUTextureView textureView) {
		this.io.setPointerField(this, 6, textureView);
		return this;
	}
	public WGPUBindGroupEntry(Pointer pointer) {
		super(pointer);
	}
}
