package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import wgpu.WgpuLibrary.WGPUBuffer;
import wgpu.WgpuLibrary.WGPUSampler;
import wgpu.WgpuLibrary.WGPUTextureView;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUBindGroupEntryExtras extends StructObject {
	public WGPUBindGroupEntryExtras() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUBindGroupEntryExtras chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : const WGPUBuffer*
	@Field(1) 
	public Pointer<WGPUBuffer > buffers() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const WGPUBuffer*
	@Field(1) 
	public WGPUBindGroupEntryExtras buffers(Pointer<WGPUBuffer > buffers) {
		this.io.setPointerField(this, 1, buffers);
		return this;
	}
	@Ptr 
	@Field(2) 
	public long bufferCount() {
		return this.io.getSizeTField(this, 2);
	}
	@Ptr 
	@Field(2) 
	public WGPUBindGroupEntryExtras bufferCount(long bufferCount) {
		this.io.setSizeTField(this, 2, bufferCount);
		return this;
	}
	/// C type : const WGPUSampler*
	@Field(3) 
	public Pointer<WGPUSampler > samplers() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : const WGPUSampler*
	@Field(3) 
	public WGPUBindGroupEntryExtras samplers(Pointer<WGPUSampler > samplers) {
		this.io.setPointerField(this, 3, samplers);
		return this;
	}
	@Ptr 
	@Field(4) 
	public long samplerCount() {
		return this.io.getSizeTField(this, 4);
	}
	@Ptr 
	@Field(4) 
	public WGPUBindGroupEntryExtras samplerCount(long samplerCount) {
		this.io.setSizeTField(this, 4, samplerCount);
		return this;
	}
	/// C type : const WGPUTextureView*
	@Field(5) 
	public Pointer<WGPUTextureView > textureViews() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : const WGPUTextureView*
	@Field(5) 
	public WGPUBindGroupEntryExtras textureViews(Pointer<WGPUTextureView > textureViews) {
		this.io.setPointerField(this, 5, textureViews);
		return this;
	}
	@Ptr 
	@Field(6) 
	public long textureViewCount() {
		return this.io.getSizeTField(this, 6);
	}
	@Ptr 
	@Field(6) 
	public WGPUBindGroupEntryExtras textureViewCount(long textureViewCount) {
		this.io.setSizeTField(this, 6, textureViewCount);
		return this;
	}
	public WGPUBindGroupEntryExtras(Pointer pointer) {
		super(pointer);
	}
}
