package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import wgpu.WgpuLibrary.WGPUCompositeAlphaMode;
import wgpu.WgpuLibrary.WGPUPresentMode;
import wgpu.WgpuLibrary.WGPUTextureFormat;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUSurfaceCapabilities extends StructObject {
	public WGPUSurfaceCapabilities() {
		super();
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public Pointer<WGPUChainedStructOut > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : WGPUChainedStructOut*
	@Field(0) 
	public WGPUSurfaceCapabilities nextInChain(Pointer<WGPUChainedStructOut > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	@Ptr 
	@Field(1) 
	public long formatCount() {
		return this.io.getSizeTField(this, 1);
	}
	@Ptr 
	@Field(1) 
	public WGPUSurfaceCapabilities formatCount(long formatCount) {
		this.io.setSizeTField(this, 1, formatCount);
		return this;
	}
	/// C type : WGPUTextureFormat*
	@Field(2) 
	public Pointer<IntValuedEnum<WGPUTextureFormat > > formats() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : WGPUTextureFormat*
	@Field(2) 
	public WGPUSurfaceCapabilities formats(Pointer<IntValuedEnum<WGPUTextureFormat > > formats) {
		this.io.setPointerField(this, 2, formats);
		return this;
	}
	@Ptr 
	@Field(3) 
	public long presentModeCount() {
		return this.io.getSizeTField(this, 3);
	}
	@Ptr 
	@Field(3) 
	public WGPUSurfaceCapabilities presentModeCount(long presentModeCount) {
		this.io.setSizeTField(this, 3, presentModeCount);
		return this;
	}
	/// C type : WGPUPresentMode*
	@Field(4) 
	public Pointer<IntValuedEnum<WGPUPresentMode > > presentModes() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : WGPUPresentMode*
	@Field(4) 
	public WGPUSurfaceCapabilities presentModes(Pointer<IntValuedEnum<WGPUPresentMode > > presentModes) {
		this.io.setPointerField(this, 4, presentModes);
		return this;
	}
	@Ptr 
	@Field(5) 
	public long alphaModeCount() {
		return this.io.getSizeTField(this, 5);
	}
	@Ptr 
	@Field(5) 
	public WGPUSurfaceCapabilities alphaModeCount(long alphaModeCount) {
		this.io.setSizeTField(this, 5, alphaModeCount);
		return this;
	}
	/// C type : WGPUCompositeAlphaMode*
	@Field(6) 
	public Pointer<IntValuedEnum<WGPUCompositeAlphaMode > > alphaModes() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : WGPUCompositeAlphaMode*
	@Field(6) 
	public WGPUSurfaceCapabilities alphaModes(Pointer<IntValuedEnum<WGPUCompositeAlphaMode > > alphaModes) {
		this.io.setPointerField(this, 6, alphaModes);
		return this;
	}
	public WGPUSurfaceCapabilities(Pointer pointer) {
		super(pointer);
	}
}
