package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUTextureSampleType;
import wgpu.WgpuLibrary.WGPUTextureViewDimension;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUTextureBindingLayout extends StructObject {
	public WGPUTextureBindingLayout() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUTextureBindingLayout nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUTextureSampleType
	@Field(1) 
	public IntValuedEnum<WGPUTextureSampleType > sampleType() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : WGPUTextureSampleType
	@Field(1) 
	public WGPUTextureBindingLayout sampleType(IntValuedEnum<WGPUTextureSampleType > sampleType) {
		this.io.setEnumField(this, 1, sampleType);
		return this;
	}
	/// C type : WGPUTextureViewDimension
	@Field(2) 
	public IntValuedEnum<WGPUTextureViewDimension > viewDimension() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : WGPUTextureViewDimension
	@Field(2) 
	public WGPUTextureBindingLayout viewDimension(IntValuedEnum<WGPUTextureViewDimension > viewDimension) {
		this.io.setEnumField(this, 2, viewDimension);
		return this;
	}
	/// C type : WGPUBool
	@Field(3) 
	public int multisampled() {
		return this.io.getIntField(this, 3);
	}
	/// C type : WGPUBool
	@Field(3) 
	public WGPUTextureBindingLayout multisampled(int multisampled) {
		this.io.setIntField(this, 3, multisampled);
		return this;
	}
	public WGPUTextureBindingLayout(Pointer pointer) {
		super(pointer);
	}
}
