package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUPushConstantRange extends StructObject {
	public WGPUPushConstantRange() {
		super();
	}
	/// C type : WGPUShaderStageFlags
	@Field(0) 
	public int stages() {
		return this.io.getIntField(this, 0);
	}
	/// C type : WGPUShaderStageFlags
	@Field(0) 
	public WGPUPushConstantRange stages(int stages) {
		this.io.setIntField(this, 0, stages);
		return this;
	}
	@Field(1) 
	public int start() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUPushConstantRange start(int start) {
		this.io.setIntField(this, 1, start);
		return this;
	}
	@Field(2) 
	public int end() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public WGPUPushConstantRange end(int end) {
		this.io.setIntField(this, 2, end);
		return this;
	}
	public WGPUPushConstantRange(Pointer pointer) {
		super(pointer);
	}
}
