package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import wgpu.WgpuLibrary.WGPUTextureDimension;
import wgpu.WgpuLibrary.WGPUTextureFormat;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUTextureDescriptor extends StructObject {
	public WGPUTextureDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUTextureDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > label() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPUTextureDescriptor label(Pointer<Byte > label) {
		this.io.setPointerField(this, 1, label);
		return this;
	}
	/// C type : WGPUTextureUsageFlags
	@Field(2) 
	public int usage() {
		return this.io.getIntField(this, 2);
	}
	/// C type : WGPUTextureUsageFlags
	@Field(2) 
	public WGPUTextureDescriptor usage(int usage) {
		this.io.setIntField(this, 2, usage);
		return this;
	}
	/// C type : WGPUTextureDimension
	@Field(3) 
	public IntValuedEnum<WGPUTextureDimension > dimension() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : WGPUTextureDimension
	@Field(3) 
	public WGPUTextureDescriptor dimension(IntValuedEnum<WGPUTextureDimension > dimension) {
		this.io.setEnumField(this, 3, dimension);
		return this;
	}
	/// C type : WGPUExtent3D
	@Field(4) 
	public WGPUExtent3D size() {
		return this.io.getNativeObjectField(this, 4);
	}
	/// C type : WGPUExtent3D
	@Field(4) 
	public WGPUTextureDescriptor size(WGPUExtent3D size) {
		this.io.setNativeObjectField(this, 4, size);
		return this;
	}
	/// C type : WGPUTextureFormat
	@Field(5) 
	public IntValuedEnum<WGPUTextureFormat > format() {
		return this.io.getEnumField(this, 5);
	}
	/// C type : WGPUTextureFormat
	@Field(5) 
	public WGPUTextureDescriptor format(IntValuedEnum<WGPUTextureFormat > format) {
		this.io.setEnumField(this, 5, format);
		return this;
	}
	@Field(6) 
	public int mipLevelCount() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public WGPUTextureDescriptor mipLevelCount(int mipLevelCount) {
		this.io.setIntField(this, 6, mipLevelCount);
		return this;
	}
	@Field(7) 
	public int sampleCount() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public WGPUTextureDescriptor sampleCount(int sampleCount) {
		this.io.setIntField(this, 7, sampleCount);
		return this;
	}
	@Ptr 
	@Field(8) 
	public long viewFormatCount() {
		return this.io.getSizeTField(this, 8);
	}
	@Ptr 
	@Field(8) 
	public WGPUTextureDescriptor viewFormatCount(long viewFormatCount) {
		this.io.setSizeTField(this, 8, viewFormatCount);
		return this;
	}
	/// C type : const WGPUTextureFormat*
	@Field(9) 
	public Pointer<IntValuedEnum<WGPUTextureFormat > > viewFormats() {
		return this.io.getPointerField(this, 9);
	}
	/// C type : const WGPUTextureFormat*
	@Field(9) 
	public WGPUTextureDescriptor viewFormats(Pointer<IntValuedEnum<WGPUTextureFormat > > viewFormats) {
		this.io.setPointerField(this, 9, viewFormats);
		return this;
	}
	public WGPUTextureDescriptor(Pointer pointer) {
		super(pointer);
	}
}
