package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUPipelineLayout;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPURenderPipelineDescriptor extends StructObject {
	public WGPURenderPipelineDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPURenderPipelineDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > label() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPURenderPipelineDescriptor label(Pointer<Byte > label) {
		this.io.setPointerField(this, 1, label);
		return this;
	}
	/// C type : WGPUPipelineLayout
	@Field(2) 
	public WGPUPipelineLayout layout() {
		return this.io.getTypedPointerField(this, 2);
	}
	/// C type : WGPUPipelineLayout
	@Field(2) 
	public WGPURenderPipelineDescriptor layout(WGPUPipelineLayout layout) {
		this.io.setPointerField(this, 2, layout);
		return this;
	}
	/// C type : WGPUVertexState
	@Field(3) 
	public WGPUVertexState vertex() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : WGPUVertexState
	@Field(3) 
	public WGPURenderPipelineDescriptor vertex(WGPUVertexState vertex) {
		this.io.setNativeObjectField(this, 3, vertex);
		return this;
	}
	/// C type : WGPUPrimitiveState
	@Field(4) 
	public WGPUPrimitiveState primitive() {
		return this.io.getNativeObjectField(this, 4);
	}
	/// C type : WGPUPrimitiveState
	@Field(4) 
	public WGPURenderPipelineDescriptor primitive(WGPUPrimitiveState primitive) {
		this.io.setNativeObjectField(this, 4, primitive);
		return this;
	}
	/// C type : const WGPUDepthStencilState*
	@Field(5) 
	public Pointer<WGPUDepthStencilState > depthStencil() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : const WGPUDepthStencilState*
	@Field(5) 
	public WGPURenderPipelineDescriptor depthStencil(Pointer<WGPUDepthStencilState > depthStencil) {
		this.io.setPointerField(this, 5, depthStencil);
		return this;
	}
	/// C type : WGPUMultisampleState
	@Field(6) 
	public WGPUMultisampleState multisample() {
		return this.io.getNativeObjectField(this, 6);
	}
	/// C type : WGPUMultisampleState
	@Field(6) 
	public WGPURenderPipelineDescriptor multisample(WGPUMultisampleState multisample) {
		this.io.setNativeObjectField(this, 6, multisample);
		return this;
	}
	/// C type : const WGPUFragmentState*
	@Field(7) 
	public Pointer<WGPUFragmentState > fragment() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : const WGPUFragmentState*
	@Field(7) 
	public WGPURenderPipelineDescriptor fragment(Pointer<WGPUFragmentState > fragment) {
		this.io.setPointerField(this, 7, fragment);
		return this;
	}
	public WGPURenderPipelineDescriptor(Pointer pointer) {
		super(pointer);
	}
}
