package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUPipelineLayout;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUShaderModuleCompilationHint extends StructObject {
	public WGPUShaderModuleCompilationHint() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUShaderModuleCompilationHint nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > entryPoint() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPUShaderModuleCompilationHint entryPoint(Pointer<Byte > entryPoint) {
		this.io.setPointerField(this, 1, entryPoint);
		return this;
	}
	/// C type : WGPUPipelineLayout
	@Field(2) 
	public WGPUPipelineLayout layout() {
		return this.io.getTypedPointerField(this, 2);
	}
	/// C type : WGPUPipelineLayout
	@Field(2) 
	public WGPUShaderModuleCompilationHint layout(WGPUPipelineLayout layout) {
		this.io.setPointerField(this, 2, layout);
		return this;
	}
	public WGPUShaderModuleCompilationHint(Pointer pointer) {
		super(pointer);
	}
}
