package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUCompilationInfo extends StructObject {
	public WGPUCompilationInfo() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUCompilationInfo nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	@Ptr 
	@Field(1) 
	public long messageCount() {
		return this.io.getSizeTField(this, 1);
	}
	@Ptr 
	@Field(1) 
	public WGPUCompilationInfo messageCount(long messageCount) {
		this.io.setSizeTField(this, 1, messageCount);
		return this;
	}
	/// C type : const WGPUCompilationMessage*
	@Field(2) 
	public Pointer<WGPUCompilationMessage > messages() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : const WGPUCompilationMessage*
	@Field(2) 
	public WGPUCompilationInfo messages(Pointer<WGPUCompilationMessage > messages) {
		this.io.setPointerField(this, 2, messages);
		return this;
	}
	public WGPUCompilationInfo(Pointer pointer) {
		super(pointer);
	}
}
