package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import wgpu.WgpuLibrary.WGPUTextureFormat;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPURenderBundleEncoderDescriptor extends StructObject {
	public WGPURenderBundleEncoderDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPURenderBundleEncoderDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > label() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPURenderBundleEncoderDescriptor label(Pointer<Byte > label) {
		this.io.setPointerField(this, 1, label);
		return this;
	}
	@Ptr 
	@Field(2) 
	public long colorFormatCount() {
		return this.io.getSizeTField(this, 2);
	}
	@Ptr 
	@Field(2) 
	public WGPURenderBundleEncoderDescriptor colorFormatCount(long colorFormatCount) {
		this.io.setSizeTField(this, 2, colorFormatCount);
		return this;
	}
	/// C type : const WGPUTextureFormat*
	@Field(3) 
	public Pointer<IntValuedEnum<WGPUTextureFormat > > colorFormats() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : const WGPUTextureFormat*
	@Field(3) 
	public WGPURenderBundleEncoderDescriptor colorFormats(Pointer<IntValuedEnum<WGPUTextureFormat > > colorFormats) {
		this.io.setPointerField(this, 3, colorFormats);
		return this;
	}
	/// C type : WGPUTextureFormat
	@Field(4) 
	public IntValuedEnum<WGPUTextureFormat > depthStencilFormat() {
		return this.io.getEnumField(this, 4);
	}
	/// C type : WGPUTextureFormat
	@Field(4) 
	public WGPURenderBundleEncoderDescriptor depthStencilFormat(IntValuedEnum<WGPUTextureFormat > depthStencilFormat) {
		this.io.setEnumField(this, 4, depthStencilFormat);
		return this;
	}
	@Field(5) 
	public int sampleCount() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public WGPURenderBundleEncoderDescriptor sampleCount(int sampleCount) {
		this.io.setIntField(this, 5, sampleCount);
		return this;
	}
	/// C type : WGPUBool
	@Field(6) 
	public int depthReadOnly() {
		return this.io.getIntField(this, 6);
	}
	/// C type : WGPUBool
	@Field(6) 
	public WGPURenderBundleEncoderDescriptor depthReadOnly(int depthReadOnly) {
		this.io.setIntField(this, 6, depthReadOnly);
		return this;
	}
	/// C type : WGPUBool
	@Field(7) 
	public int stencilReadOnly() {
		return this.io.getIntField(this, 7);
	}
	/// C type : WGPUBool
	@Field(7) 
	public WGPURenderBundleEncoderDescriptor stencilReadOnly(int stencilReadOnly) {
		this.io.setIntField(this, 7, stencilReadOnly);
		return this;
	}
	public WGPURenderBundleEncoderDescriptor(Pointer pointer) {
		super(pointer);
	}
}
