package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUMultisampleState extends StructObject {
	public WGPUMultisampleState() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUMultisampleState nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	@Field(1) 
	public int count() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUMultisampleState count(int count) {
		this.io.setIntField(this, 1, count);
		return this;
	}
	@Field(2) 
	public int mask() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public WGPUMultisampleState mask(int mask) {
		this.io.setIntField(this, 2, mask);
		return this;
	}
	/// C type : WGPUBool
	@Field(3) 
	public int alphaToCoverageEnabled() {
		return this.io.getIntField(this, 3);
	}
	/// C type : WGPUBool
	@Field(3) 
	public WGPUMultisampleState alphaToCoverageEnabled(int alphaToCoverageEnabled) {
		this.io.setIntField(this, 3, alphaToCoverageEnabled);
		return this;
	}
	public WGPUMultisampleState(Pointer pointer) {
		super(pointer);
	}
}
