package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUBuffer;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUImageCopyBuffer extends StructObject {
	public WGPUImageCopyBuffer() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUImageCopyBuffer nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUTextureDataLayout
	@Field(1) 
	public WGPUTextureDataLayout layout() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : WGPUTextureDataLayout
	@Field(1) 
	public WGPUImageCopyBuffer layout(WGPUTextureDataLayout layout) {
		this.io.setNativeObjectField(this, 1, layout);
		return this;
	}
	/// C type : WGPUBuffer
	@Field(2) 
	public WGPUBuffer buffer() {
		return this.io.getTypedPointerField(this, 2);
	}
	/// C type : WGPUBuffer
	@Field(2) 
	public WGPUImageCopyBuffer buffer(WGPUBuffer buffer) {
		this.io.setPointerField(this, 2, buffer);
		return this;
	}
	public WGPUImageCopyBuffer(Pointer pointer) {
		super(pointer);
	}
}
