package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUBindGroupLayoutEntryExtras extends StructObject {
	public WGPUBindGroupLayoutEntryExtras() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUBindGroupLayoutEntryExtras chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Field(1) 
	public int count() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUBindGroupLayoutEntryExtras count(int count) {
		this.io.setIntField(this, 1, count);
		return this;
	}
	public WGPUBindGroupLayoutEntryExtras(Pointer pointer) {
		super(pointer);
	}
}
