package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUPipelineLayoutExtras extends StructObject {
	public WGPUPipelineLayoutExtras() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUPipelineLayoutExtras chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	@Ptr 
	@Field(1) 
	public long pushConstantRangeCount() {
		return this.io.getSizeTField(this, 1);
	}
	@Ptr 
	@Field(1) 
	public WGPUPipelineLayoutExtras pushConstantRangeCount(long pushConstantRangeCount) {
		this.io.setSizeTField(this, 1, pushConstantRangeCount);
		return this;
	}
	/// C type : const WGPUPushConstantRange*
	@Field(2) 
	public Pointer<WGPUPushConstantRange > pushConstantRanges() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : const WGPUPushConstantRange*
	@Field(2) 
	public WGPUPipelineLayoutExtras pushConstantRanges(Pointer<WGPUPushConstantRange > pushConstantRanges) {
		this.io.setPointerField(this, 2, pushConstantRanges);
		return this;
	}
	public WGPUPipelineLayoutExtras(Pointer pointer) {
		super(pointer);
	}
}
