package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUOrigin3D extends StructObject {
	public WGPUOrigin3D() {
		super();
	}
	@Field(0) 
	public int x() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public WGPUOrigin3D x(int x) {
		this.io.setIntField(this, 0, x);
		return this;
	}
	@Field(1) 
	public int y() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUOrigin3D y(int y) {
		this.io.setIntField(this, 1, y);
		return this;
	}
	@Field(2) 
	public int z() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public WGPUOrigin3D z(int z) {
		this.io.setIntField(this, 2, z);
		return this;
	}
	public WGPUOrigin3D(Pointer pointer) {
		super(pointer);
	}
}
