package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUBufferBindingType;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUBufferBindingLayout extends StructObject {
	public WGPUBufferBindingLayout() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUBufferBindingLayout nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUBufferBindingType
	@Field(1) 
	public IntValuedEnum<WGPUBufferBindingType > type() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : WGPUBufferBindingType
	@Field(1) 
	public WGPUBufferBindingLayout type(IntValuedEnum<WGPUBufferBindingType > type) {
		this.io.setEnumField(this, 1, type);
		return this;
	}
	/// C type : WGPUBool
	@Field(2) 
	public int hasDynamicOffset() {
		return this.io.getIntField(this, 2);
	}
	/// C type : WGPUBool
	@Field(2) 
	public WGPUBufferBindingLayout hasDynamicOffset(int hasDynamicOffset) {
		this.io.setIntField(this, 2, hasDynamicOffset);
		return this;
	}
	@Field(3) 
	public long minBindingSize() {
		return this.io.getLongField(this, 3);
	}
	@Field(3) 
	public WGPUBufferBindingLayout minBindingSize(long minBindingSize) {
		this.io.setLongField(this, 3, minBindingSize);
		return this;
	}
	public WGPUBufferBindingLayout(Pointer pointer) {
		super(pointer);
	}
}
