package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUStorageTextureAccess;
import wgpu.WgpuLibrary.WGPUTextureFormat;
import wgpu.WgpuLibrary.WGPUTextureViewDimension;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUStorageTextureBindingLayout extends StructObject {
	public WGPUStorageTextureBindingLayout() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUStorageTextureBindingLayout nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : WGPUStorageTextureAccess
	@Field(1) 
	public IntValuedEnum<WGPUStorageTextureAccess > access() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : WGPUStorageTextureAccess
	@Field(1) 
	public WGPUStorageTextureBindingLayout access(IntValuedEnum<WGPUStorageTextureAccess > access) {
		this.io.setEnumField(this, 1, access);
		return this;
	}
	/// C type : WGPUTextureFormat
	@Field(2) 
	public IntValuedEnum<WGPUTextureFormat > format() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : WGPUTextureFormat
	@Field(2) 
	public WGPUStorageTextureBindingLayout format(IntValuedEnum<WGPUTextureFormat > format) {
		this.io.setEnumField(this, 2, format);
		return this;
	}
	/// C type : WGPUTextureViewDimension
	@Field(3) 
	public IntValuedEnum<WGPUTextureViewDimension > viewDimension() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : WGPUTextureViewDimension
	@Field(3) 
	public WGPUStorageTextureBindingLayout viewDimension(IntValuedEnum<WGPUTextureViewDimension > viewDimension) {
		this.io.setEnumField(this, 3, viewDimension);
		return this;
	}
	public WGPUStorageTextureBindingLayout(Pointer pointer) {
		super(pointer);
	}
}
