package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUBackendType;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUGlobalReport extends StructObject {
	public WGPUGlobalReport() {
		super();
	}
	/// C type : WGPURegistryReport
	@Field(0) 
	public WGPURegistryReport surfaces() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPURegistryReport
	@Field(0) 
	public WGPUGlobalReport surfaces(WGPURegistryReport surfaces) {
		this.io.setNativeObjectField(this, 0, surfaces);
		return this;
	}
	/// C type : WGPUBackendType
	@Field(1) 
	public IntValuedEnum<WGPUBackendType > backendType() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : WGPUBackendType
	@Field(1) 
	public WGPUGlobalReport backendType(IntValuedEnum<WGPUBackendType > backendType) {
		this.io.setEnumField(this, 1, backendType);
		return this;
	}
	/// C type : WGPUHubReport
	@Field(2) 
	public WGPUHubReport vulkan() {
		return this.io.getNativeObjectField(this, 2);
	}
	/// C type : WGPUHubReport
	@Field(2) 
	public WGPUGlobalReport vulkan(WGPUHubReport vulkan) {
		this.io.setNativeObjectField(this, 2, vulkan);
		return this;
	}
	/// C type : WGPUHubReport
	@Field(3) 
	public WGPUHubReport metal() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : WGPUHubReport
	@Field(3) 
	public WGPUGlobalReport metal(WGPUHubReport metal) {
		this.io.setNativeObjectField(this, 3, metal);
		return this;
	}
	/// C type : WGPUHubReport
	@Field(4) 
	public WGPUHubReport dx12() {
		return this.io.getNativeObjectField(this, 4);
	}
	/// C type : WGPUHubReport
	@Field(4) 
	public WGPUGlobalReport dx12(WGPUHubReport dx12) {
		this.io.setNativeObjectField(this, 4, dx12);
		return this;
	}
	/// C type : WGPUHubReport
	@Field(5) 
	public WGPUHubReport gl() {
		return this.io.getNativeObjectField(this, 5);
	}
	/// C type : WGPUHubReport
	@Field(5) 
	public WGPUGlobalReport gl(WGPUHubReport gl) {
		this.io.setNativeObjectField(this, 5, gl);
		return this;
	}
	public WGPUGlobalReport(Pointer pointer) {
		super(pointer);
	}
}
