package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUBlendState extends StructObject {
	public WGPUBlendState() {
		super();
	}
	/// C type : WGPUBlendComponent
	@Field(0) 
	public WGPUBlendComponent color() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUBlendComponent
	@Field(0) 
	public WGPUBlendState color(WGPUBlendComponent color) {
		this.io.setNativeObjectField(this, 0, color);
		return this;
	}
	/// C type : WGPUBlendComponent
	@Field(1) 
	public WGPUBlendComponent alpha() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : WGPUBlendComponent
	@Field(1) 
	public WGPUBlendState alpha(WGPUBlendComponent alpha) {
		this.io.setNativeObjectField(this, 1, alpha);
		return this;
	}
	public WGPUBlendState(Pointer pointer) {
		super(pointer);
	}
}
