package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUNativeLimits extends StructObject {
	public WGPUNativeLimits() {
		super();
	}
	@Field(0) 
	public int maxPushConstantSize() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public WGPUNativeLimits maxPushConstantSize(int maxPushConstantSize) {
		this.io.setIntField(this, 0, maxPushConstantSize);
		return this;
	}
	@Field(1) 
	public int maxNonSamplerBindings() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUNativeLimits maxNonSamplerBindings(int maxNonSamplerBindings) {
		this.io.setIntField(this, 1, maxNonSamplerBindings);
		return this;
	}
	public WGPUNativeLimits(Pointer pointer) {
		super(pointer);
	}
}
