package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUBindGroupLayoutEntry extends StructObject {
	public WGPUBindGroupLayoutEntry() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUBindGroupLayoutEntry nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	@Field(1) 
	public int binding() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public WGPUBindGroupLayoutEntry binding(int binding) {
		this.io.setIntField(this, 1, binding);
		return this;
	}
	/// C type : WGPUShaderStageFlags
	@Field(2) 
	public int visibility() {
		return this.io.getIntField(this, 2);
	}
	/// C type : WGPUShaderStageFlags
	@Field(2) 
	public WGPUBindGroupLayoutEntry visibility(int visibility) {
		this.io.setIntField(this, 2, visibility);
		return this;
	}
	/// C type : WGPUBufferBindingLayout
	@Field(3) 
	public WGPUBufferBindingLayout buffer() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : WGPUBufferBindingLayout
	@Field(3) 
	public WGPUBindGroupLayoutEntry buffer(WGPUBufferBindingLayout buffer) {
		this.io.setNativeObjectField(this, 3, buffer);
		return this;
	}
	/// C type : WGPUSamplerBindingLayout
	@Field(4) 
	public WGPUSamplerBindingLayout sampler() {
		return this.io.getNativeObjectField(this, 4);
	}
	/// C type : WGPUSamplerBindingLayout
	@Field(4) 
	public WGPUBindGroupLayoutEntry sampler(WGPUSamplerBindingLayout sampler) {
		this.io.setNativeObjectField(this, 4, sampler);
		return this;
	}
	/// C type : WGPUTextureBindingLayout
	@Field(5) 
	public WGPUTextureBindingLayout texture() {
		return this.io.getNativeObjectField(this, 5);
	}
	/// C type : WGPUTextureBindingLayout
	@Field(5) 
	public WGPUBindGroupLayoutEntry texture(WGPUTextureBindingLayout texture) {
		this.io.setNativeObjectField(this, 5, texture);
		return this;
	}
	/// C type : WGPUStorageTextureBindingLayout
	@Field(6) 
	public WGPUStorageTextureBindingLayout storageTexture() {
		return this.io.getNativeObjectField(this, 6);
	}
	/// C type : WGPUStorageTextureBindingLayout
	@Field(6) 
	public WGPUBindGroupLayoutEntry storageTexture(WGPUStorageTextureBindingLayout storageTexture) {
		this.io.setNativeObjectField(this, 6, storageTexture);
		return this;
	}
	public WGPUBindGroupLayoutEntry(Pointer pointer) {
		super(pointer);
	}
}
