package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import wgpu.WgpuLibrary.WGPUQuerySet;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPURenderPassDescriptor extends StructObject {
	public WGPURenderPassDescriptor() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPURenderPassDescriptor nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > label() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPURenderPassDescriptor label(Pointer<Byte > label) {
		this.io.setPointerField(this, 1, label);
		return this;
	}
	@Ptr 
	@Field(2) 
	public long colorAttachmentCount() {
		return this.io.getSizeTField(this, 2);
	}
	@Ptr 
	@Field(2) 
	public WGPURenderPassDescriptor colorAttachmentCount(long colorAttachmentCount) {
		this.io.setSizeTField(this, 2, colorAttachmentCount);
		return this;
	}
	/// C type : const WGPURenderPassColorAttachment*
	@Field(3) 
	public Pointer<WGPURenderPassColorAttachment > colorAttachments() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : const WGPURenderPassColorAttachment*
	@Field(3) 
	public WGPURenderPassDescriptor colorAttachments(Pointer<WGPURenderPassColorAttachment > colorAttachments) {
		this.io.setPointerField(this, 3, colorAttachments);
		return this;
	}
	/// C type : const WGPURenderPassDepthStencilAttachment*
	@Field(4) 
	public Pointer<WGPURenderPassDepthStencilAttachment > depthStencilAttachment() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : const WGPURenderPassDepthStencilAttachment*
	@Field(4) 
	public WGPURenderPassDescriptor depthStencilAttachment(Pointer<WGPURenderPassDepthStencilAttachment > depthStencilAttachment) {
		this.io.setPointerField(this, 4, depthStencilAttachment);
		return this;
	}
	/// C type : WGPUQuerySet
	@Field(5) 
	public WGPUQuerySet occlusionQuerySet() {
		return this.io.getTypedPointerField(this, 5);
	}
	/// C type : WGPUQuerySet
	@Field(5) 
	public WGPURenderPassDescriptor occlusionQuerySet(WGPUQuerySet occlusionQuerySet) {
		this.io.setPointerField(this, 5, occlusionQuerySet);
		return this;
	}
	/// C type : const WGPURenderPassTimestampWrites*
	@Field(6) 
	public Pointer<WGPURenderPassTimestampWrites > timestampWrites() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : const WGPURenderPassTimestampWrites*
	@Field(6) 
	public WGPURenderPassDescriptor timestampWrites(Pointer<WGPURenderPassTimestampWrites > timestampWrites) {
		this.io.setPointerField(this, 6, timestampWrites);
		return this;
	}
	public WGPURenderPassDescriptor(Pointer pointer) {
		super(pointer);
	}
}
