package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import wgpu.WgpuLibrary.WGPUCompilationMessageType;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUCompilationMessage extends StructObject {
	public WGPUCompilationMessage() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUCompilationMessage nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	/// C type : const char*
	@Field(1) 
	public Pointer<Byte > message() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const char*
	@Field(1) 
	public WGPUCompilationMessage message(Pointer<Byte > message) {
		this.io.setPointerField(this, 1, message);
		return this;
	}
	/// C type : WGPUCompilationMessageType
	@Field(2) 
	public IntValuedEnum<WGPUCompilationMessageType > type() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : WGPUCompilationMessageType
	@Field(2) 
	public WGPUCompilationMessage type(IntValuedEnum<WGPUCompilationMessageType > type) {
		this.io.setEnumField(this, 2, type);
		return this;
	}
	@Field(3) 
	public long lineNum() {
		return this.io.getLongField(this, 3);
	}
	@Field(3) 
	public WGPUCompilationMessage lineNum(long lineNum) {
		this.io.setLongField(this, 3, lineNum);
		return this;
	}
	@Field(4) 
	public long linePos() {
		return this.io.getLongField(this, 4);
	}
	@Field(4) 
	public WGPUCompilationMessage linePos(long linePos) {
		this.io.setLongField(this, 4, linePos);
		return this;
	}
	@Field(5) 
	public long offset() {
		return this.io.getLongField(this, 5);
	}
	@Field(5) 
	public WGPUCompilationMessage offset(long offset) {
		this.io.setLongField(this, 5, offset);
		return this;
	}
	@Field(6) 
	public long length() {
		return this.io.getLongField(this, 6);
	}
	@Field(6) 
	public WGPUCompilationMessage length(long length) {
		this.io.setLongField(this, 6, length);
		return this;
	}
	@Field(7) 
	public long utf16LinePos() {
		return this.io.getLongField(this, 7);
	}
	@Field(7) 
	public WGPUCompilationMessage utf16LinePos(long utf16LinePos) {
		this.io.setLongField(this, 7, utf16LinePos);
		return this;
	}
	@Field(8) 
	public long utf16Offset() {
		return this.io.getLongField(this, 8);
	}
	@Field(8) 
	public WGPUCompilationMessage utf16Offset(long utf16Offset) {
		this.io.setLongField(this, 8, utf16Offset);
		return this;
	}
	@Field(9) 
	public long utf16Length() {
		return this.io.getLongField(this, 9);
	}
	@Field(9) 
	public WGPUCompilationMessage utf16Length(long utf16Length) {
		this.io.setLongField(this, 9, utf16Length);
		return this;
	}
	public WGPUCompilationMessage(Pointer pointer) {
		super(pointer);
	}
}
