package wgpu;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import wgpu.WgpuLibrary.WGPUPipelineStatisticName;
/**
 * <i>native declaration : wgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUQuerySetDescriptorExtras extends StructObject {
	public WGPUQuerySetDescriptorExtras() {
		super();
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUChainedStruct chain() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : WGPUChainedStruct
	@Field(0) 
	public WGPUQuerySetDescriptorExtras chain(WGPUChainedStruct chain) {
		this.io.setNativeObjectField(this, 0, chain);
		return this;
	}
	/// C type : const WGPUPipelineStatisticName*
	@Field(1) 
	public Pointer<IntValuedEnum<WGPUPipelineStatisticName > > pipelineStatistics() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : const WGPUPipelineStatisticName*
	@Field(1) 
	public WGPUQuerySetDescriptorExtras pipelineStatistics(Pointer<IntValuedEnum<WGPUPipelineStatisticName > > pipelineStatistics) {
		this.io.setPointerField(this, 1, pipelineStatistics);
		return this;
	}
	@Ptr 
	@Field(2) 
	public long pipelineStatisticCount() {
		return this.io.getSizeTField(this, 2);
	}
	@Ptr 
	@Field(2) 
	public WGPUQuerySetDescriptorExtras pipelineStatisticCount(long pipelineStatisticCount) {
		this.io.setSizeTField(this, 2, pipelineStatisticCount);
		return this;
	}
	public WGPUQuerySetDescriptorExtras(Pointer pointer) {
		super(pointer);
	}
}
