package wgpu;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : webgpu.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("wgpu") 
public class WGPUTextureDataLayout extends StructObject {
	public WGPUTextureDataLayout() {
		super();
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public Pointer<WGPUChainedStruct > nextInChain() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : const WGPUChainedStruct*
	@Field(0) 
	public WGPUTextureDataLayout nextInChain(Pointer<WGPUChainedStruct > nextInChain) {
		this.io.setPointerField(this, 0, nextInChain);
		return this;
	}
	@Field(1) 
	public long offset() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public WGPUTextureDataLayout offset(long offset) {
		this.io.setLongField(this, 1, offset);
		return this;
	}
	@Field(2) 
	public int bytesPerRow() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public WGPUTextureDataLayout bytesPerRow(int bytesPerRow) {
		this.io.setIntField(this, 2, bytesPerRow);
		return this;
	}
	@Field(3) 
	public int rowsPerImage() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public WGPUTextureDataLayout rowsPerImage(int rowsPerImage) {
		this.io.setIntField(this, 3, rowsPerImage);
		return this;
	}
	public WGPUTextureDataLayout(Pointer pointer) {
		super(pointer);
	}
}
